### ISSUE TITLE
Stories made with Story Editor + 2019 Landsat have their waypoints in the wrong location

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/data-visualization-tools#102]
Waypoints made with the Story Editor use pixel coordinates for the views. This unfortunately means that if a waypoint is made this way and the layers it use are lat/lng based and the projection changes (as was the case with the latest Landsat layer), they will no longer be at the right location.

**Comment by rsargent** [comment]
Probably related:  zoom levels appeared to change even with latlng views in the transition between landsat dimensions.  From test by @hjhawkinsiv , here's earthtime.org with new landsat, versus a dev site with old landsat, showing first waypoint of Sahel in Peril:

![legend_sahel (2)](https://user-images.githubusercontent.com/324851/82120854-e8fb8200-9756-11ea-8823-12361887f833.png)
![default_sahel (2)](https://user-images.githubusercontent.com/324851/82120859-ee58cc80-9756-11ea-8bb0-97dd0c91dd7b.png)

**Comment by rsargent** [comment]
Might it make sense to have an EarthTime mode for timelapse.js where we interpret pixel views and zoom/scale based on original landsat dimensions, and set that coordinate system in stone moving forward?

**Comment by rsargent** [comment]
Consistent coordinate system implemented in the refactor branch and released.  Closing bug.
