### ISSUE TITLE
Persisting "Loaded (L)" text

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#108]
"Loaded (L)" text persists in EarthTime stories, after rendering has completed on the server.

This is of particular annoyance to WEF users. Either making this non-visible or adding a time out after the rendering so that the text does not persist are both possible solutions. It is particularly unclear to users as it is mostly an indicator of the server rendering status, and does not correlate to whether the viewer's page has actually finished loading.

![image](https://user-images.githubusercontent.com/42879120/84435852-7c15c380-ac00-11ea-81af-2b605a98ba3c.png)

**Comment by rsargent** [comment]
Paul and I are 100% happy to make this disappear after load is
complete instead of saying Loaded (L) / (P)

**Comment by pdille** [comment]
This has been fixed for awhile, so closing now.
