### ISSUE TITLE
Permanent Spinner if Layer Selected and Un-selected before Load Completed

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#111]
This issue became manifest during layer testing by @hjhawkinsiv but is easily reproducible manually. A good example can be seen in the Biodiversity layers. If a user clicks and un-clicks on layer check boxes quickly, eventually some layers will freeze in a sort of liminal space. The spinner stays permanently both on the map and next to the layer name. Additional layers can be selected, and their legends will be added to the map, but their data will not be drawn while EarthTime is stuck in this state.

An example of this state can be seen in this image:
![image](https://user-images.githubusercontent.com/42879120/86034187-1bf88d00-ba08-11ea-9d0d-92b707e21009.png)

The only way to break out of this state seems to be to re-select the problem layer and let it fully load before un-selecting and moving on.

Is this likely to be addressed by Layer DB and other current code improvements? Or is this happening at a different place in the code?

**Comment by rsargent** [comment]
I think likely this will go away when get get LayerDB up.

**Comment by pdille** [comment]
Should be addressed with layerDB changes and further improved in 83860da
