### ISSUE TITLE
timelapse.lastFrameCompletelyDrawn not returning 'true'

### ISSUE THREAD

**Issue by hjhawkinsiv** [CMU-CREATE-Lab/data-visualization-tools#112]
Discovered this while testing layer load times. Specifically and consistently with the 'GDP PPP' layer under 'Economics'. The image below is from manually clicking on the layer.

![EarthTime GDP PPP Not Loading](https://user-images.githubusercontent.com/8990930/86644024-064c1000-bf92-11ea-981e-6d466fe3d091.PNG)

It stalls on this black background and checking `timelapse.lastFrameCompletelyDrawn` returns `false`. Deselecting and selecting the layer doesn't seem to solve this, but reloading the page and trying it again does help more often than not. Though, for Selenium testing purposes, reloading the page invalidates all elements accessed prior to it.

**Comment by pdille** [comment]
@hjhawkinsiv Can you check this again on the staging site? Would be good to know if this is happening on the new code base, though maybe too much is still in flux there to know for sure.

**Comment by rsargent** [comment]
No longer using this codebase.  Please reopen if the same issue appears in the new codebase
