### ISSUE TITLE
Himawari Imagery Missing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#117]
https://staging.earthtime.org/stories/top_50#waypointIdx=18&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

No Himawari8 imagery being displayed

**Comment by pdille** [comment]
Himawari shows up as of commit 89ec696 but there are still timeline issues around it.

**Comment by pdille** [comment]
Himawari (and technically any other timemachine that pulls capture times from tm.json) has a timeline as of commit e860c9e

**Comment by jjkohler** [comment]
Closed due to the tm.json issue being raised elsewhere.
