### ISSUE TITLE
Landsat not shown

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#118]
No Landsat layers are showing image tiles
Example:
https://staging.earthtime.org/stories/top_50#waypointIdx=0&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by pdille** [comment]
Should be fixed as of commit 89ec696

**Comment by pdille** [comment]
Also note that the specific waypoint in that story "stutters" like that because it is set to loop over the first year. That waypoint seems invalid and should have a ps=0 if we are doing a paused year. Would be curious to know where the waypoint came from and how it behaved before.
