### ISSUE TITLE
Bubble Map Not Loading

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#119]
https://staging.earthtime.org/stories/top_50#waypointIdx=19&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

This layer appears to be a combination of both bubble and and dot map content and none of it currently loads

**Comment by pdille** [comment]
Bubble map appears of commit 89ec696.  The dot map one is still failing though. See discussion around dot maps in issue #115
