### ISSUE TITLE
Coral only Data Layer missing from spreadsheet

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#120]
https://staging.earthtime.org/stories/top_50#waypointIdx=21&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

Coral Reef Combo layer not loading

**Comment by pdille** [comment]
Combo layers should now be loading as of commit e860c9e, though in the above example the coral only layer has not yet made it into the spreadsheet.

**Comment by jjkohler** [comment]
Issue name changed due to @pdille fix of original underlying issue.

**Comment by jjkohler** [comment]
This issue will be fixed when all layers are successfully removed from index.ts

**Comment by pdille** [comment]
Should be fixed now. Please confirm.
