### ISSUE TITLE
Layers need removed from index.ts

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#121]
A few particularly complex layers need removed from index.ts

Layers that still need removed:

LODES, annual refugee returns, sea level rise, active mining, IOM IDPs, china infrastructure (4 individual layers), city labels, s&p crude layers (9 layers), coral locations, and wind layer

4-5 timemachines will be dealt with by Paul

**Comment by gabrielo** [comment]
All layers that were shared via sharelinks are out. Some are still buggy but will be detailed in additional issues.
