### ISSUE TITLE
Transcoding of refactor code into older JS and older browser testing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#122]
Currently we are not trans-coding into older JS - testing needed for backwards compatibility into older browsers

**Comment by rsargent** [comment]
## Desktop Explore
* Mac Chrome, FF, Safari.  test against current minus 2
* Windows Chrome, FF.  test against current minus 2.  No IE
* Chromebook: Chrome
    * Harry will take Lab Chromebook testing machine

## Mobile scrolling stories
* Android 6+
  * Chrome
  * Samsung (3.5%)
* iOS 13, 14
  * Mobile safari
  * Old test iPad from lab: Harry
  * New iPhone: Jared

## Mobile explore
  Not in scope for initial release

**Comment by rsargent** [comment]
Add JS instrumentation package to record console logged errors so we can see if there are commonly browser incompatibilities in the real world.

**Comment by rsargent** [comment]
Randy will track down the service(s) and share with Gabriel

**Comment by pdille** [comment]
@gabrielo At the last meeting you mentioned the error logging service was implemented. How exactly do we make use of it? Thanks!

**Comment by gabrielo** [comment]
@pdille Invitations sent.

@rsargent If after looking at the platform in action we should consider upgrading to the paid business plan. Free plan only records 5K errors per month and allows a single extra team member.

**Comment by jjkohler** [comment]
This has been replaced by the error logging that @gabrielo has implemented.
