### ISSUE TITLE
Pull dates from tm.json for timemachines that are missing continuous dates

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#124]
Timeline are missing from timemachines (e.g. Himawari8 and Ocean Salinity)

Himawari8 Example:
https://staging.earthtime.org/stories/top_50#waypointIdx=34&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by pdille** [comment]
Timelines show up for timemachines except for ones that do not have a start/end date defined in the spreadsheet. This is any timemachine that does not have a continuous set of dates and thus we need to pull the dates from the corresponding tm.json

**Comment by jjkohler** [comment]
Renamed to reflect current work progress.

**Comment by jjkohler** [comment]
Finished last week.
