### ISSUE TITLE
EXTRAS Content Not Visible

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#128]
Extras content such as still images and external video content not displaying 

Example:
https://staging.earthtime.org/stories/top_50#waypointIdx=16&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by jjkohler** [comment]
Extras Content NOW Visible

**Comment by jjkohler** [comment]
We're ALMOST there, but not quite yet.
![image](https://user-images.githubusercontent.com/42879120/96166298-c929df00-0eeb-11eb-842c-432f8f12e8e7.png)
When appearing in a story extra content images often do not appear when the waypoint is first loaded - only showing up after a second click on the waypoint or leaving the waypoint and returning. After an extra waypoint HAS correctly loaded it persists upon revisiting, but first load of each waypoint is unstable.

**Comment by pdille** [comment]
Take 2 on this. The race condition should be fixed. Please confirm.

**Comment by jjkohler** [comment]
2nd time's the charm.
