### ISSUE TITLE
earthtime.org zoom/projection errors make it difficult to regression test refactor.earthtime.org

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#129]

**Comment by rsargent** [comment]
Paul and I tracked this down.  RTFL branch appears to be correct, and earthtime.org is incorrect due to Landsat basemap change earlier this year.  It's unclear whether we should fix the main branch, or ignore projection differences for now until we bring RTFL online

**Comment by rsargent** [comment]
davos2019 looks to be okay projectionwise.  I'm going to try creating "golden.earthtime.org" and find the most recent code prior to the regression.

**Comment by rsargent** [comment]
golden.earthtime.org seems to have fixed the projection for latlon and pixel waypoints.
It's unclear why attempts to make earthtime.org use the older projection didn't pan out.
