### ISSUE TITLE
Per Layer Draw Function

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#130]
Implementation of throttling code needs revisited in refactor branch.

**Comment by jjkohler** [comment]
In process. Just being tested.

**Comment by rsargent** [comment]
Per-layer draw function for animated and static dotmaps committed in 50585e74928854a765504fb96ac037b77edbfa26 and 9b284a587a0bada83e561eb165a1c8475a8f4fa2.

Waiting for Gabriel's LODES commit to have test case for specifying layer draw function in spreadsheet.

**Comment by gabrielo** [comment]
Addded in commit 36a11d977f747567851a13d7d7d6f287ebdec762

**Comment by pdille** [comment]
@rsargent Was there anything you wanted to test here now that LODES draw function is in place?

**Comment by rsargent** [comment]
My understanding is Gabriel completed this in 36a11d9.  I'll close this issue.
