### ISSUE TITLE
Basemap credits logic missing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#131]
Example:
Expected Behavior
https://earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-12.92014,13.91479,-0.014,latLng&t=0.6&ps=50&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0

Current Refactor Behavior:
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=4.56342,13.91479,0,latLng&t=0.37&ps=50&l=bdrk,ar&bt=20000101&et=20151231&startDwell=0&endDwell=0

**Comment by pdille** [comment]
Should be fixed in commit b4018e2bfbfa

**Comment by jjkohler** [comment]
Due to the fact that this fix has now implemented correct behavior, some credits will not match those shown in golden.earthtime. This is due to the fact that the new logic only shows the credit for the actual displayed layer, and not other basemaps that might be included in a share link. The fix appears to be working across staging layers.
