### ISSUE TITLE
Logic Missing for UI Shifting

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#133]
UI remains in position appropriate for timeline, even when no timeline present.
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.43457,-79.91635,9.796,latLng&t=0&ps=50&l=bdrk_detailed,acs2016_public_assistance&bt=19840101&et=20181231&startDwell=0&endDwell=0

**Comment by pdille** [comment]
Should be resolved as of commit 808594a9be Please confirm

**Comment by jjkohler** [comment]
See no more evidence of this issue and closing!
