### ISSUE TITLE
Bubble zoom-level scaling not per original ET behavior

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#134]
Current
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=4.56342,9.08729,3.523,latLng&t=1.37&ps=50&l=bdrk,uf&bt=20000101&et=20151231&startDwell=0&endDwell=0

Expected:
https://earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=17.59725,9.08728,-1.601,latLng&t=1.53&ps=50&l=bdrk,uf&bt=20000101&et=20151231&startDwell=0&endDwell=0

**Comment by pdille** [comment]
FYI, if you look at the original ("golden") https://earthtime.org/WebGLVectorTile2.js file and then search for
"zoom +" (without quotes) you should (I believe) find the 18 places where we need to go back to gEarthTime.timelapseZoom(), **rather** than the now gEarthTime.gmapsZoomLevel().  Urban fragility, the specific layer in question in the links above in one such of these. @gabrielo

**Comment by jjkohler** [comment]
@gabrielo could you take a look at this?

**Comment by gabrielo** [comment]
Should be corrected with commit 3a10e8dec55bcf33ff91d11d7b8ea87853f7e6c5

For testing purposes compare the following affected visualizations:
https://golden.earthtime.org/stories/zoom_size_issues#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0
https://staging.earthtime.org/stories/zoom_size_issues#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by jjkohler** [comment]
This issue appears to have been resolved!
