### ISSUE TITLE
Country Outlines Missing (possible draw order issue)

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#135]
Example:
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=5.53124,8.44479,0.525,latLng&t=4.28&ps=50&l=blsat,berkeley-earth-temperature-anomaly-v2-yearly&bt=18500101&et=20181231&startDwell=0&endDwell=0

**Comment by rsargent** [comment]
Is this fixed?  Here's what I'm currently seeing:
![image](https://user-images.githubusercontent.com/324851/94681244-1a817e00-02f1-11eb-9e03-1c31b140ec77.png)
