### ISSUE TITLE
Background Map showing behind City Lights Layer

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#136]
Example:
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=21.95897,-3.36528,0.17,latLng&t=1.6&ps=50&l=blsat,lan&bt=19840101&et=20191231&startDwell=0&endDwell=0

Compare:
https://earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=37.92783,-3.36528,0.17,latLng&t=1.6&ps=50&l=lan,blsat&bt=19840101&et=20191231&startDwell=0&endDwell=0

**Comment by rsargent** [comment]
Manually removing blsat from the sharelink makes the view look as originally intended, but it would be impossible to modify all extant stories and bookmarked share links

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=21.95897,-3.36528,0.17,latLng&t=1.6&ps=50&l=lan&bt=19840101&et=20191231&startDwell=0&endDwell=0

Backwards compatibility requires applying constraints when parsing sharelinks

Flagging for Paul and I to discuss

**Comment by rsargent** [comment]
Fixed in commit fc3020ef1dc0b7113cf37a7fe01af657a2182bdb
