### ISSUE TITLE
Loading of lower zoom detail-level tiles in basemap

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#138]
Currently ET loads the more appropriate detail base layer:
![image](https://user-images.githubusercontent.com/42879120/94726561-68b37300-032b-11eb-955e-c174a0d0dadd.png)
https://earthtime.org/explore#v=40.44103,-79.95157,11.145,latLng&t=3.3&ps=50&l=bdrk,bdrk_detailed,acs2016_all_income&bt=19840101&et=20191231&startDwell=0&endDwell=0

While Refactor shows the less detailed tiles
![image](https://user-images.githubusercontent.com/42879120/94726638-82ed5100-032b-11eb-93d8-9f4fa3d355ac.png)

https://staging.earthtime.org/explore#v=40.44845,-79.95432,10.254,latLng&t=1.31&ps=50&l=bdrk_detailed,acs2016_all_income&bt=19840101&et=20191231&startDwell=0&endDwell=0

This does not seem fully explained by the differences in projection or waypoints. Even when zoomed to nearly exactly equivalent zoom levels, the underlying base map detail level is different.

**Comment by rsargent** [comment]
With just bdrk_detailed, comparing with golden.earthtime.org:
https://golden.earthtime.org/explore#v=40.39317,-79.88281,10.2,latLng&l=bdrk_detailed
https://staging.earthtime.org/explore#v=40.39317,-79.88281,10.2,latLng&l=bdrk_detailed
![compare](https://user-images.githubusercontent.com/324851/94989276-6e82a180-0541-11eb-928f-bb8020547694.gif)

Some zooms+window sizes look identical, some are coarser with staging.

**Comment by rsargent** [comment]
Fixed in commit acf40839b7f4451752aac5cab3cb38a299ffa6da

**Comment by jjkohler** [comment]
![image](https://user-images.githubusercontent.com/42879120/95484326-54d8c400-095e-11eb-923d-9009379ab8b9.png)

![image](https://user-images.githubusercontent.com/42879120/95484560-9cf7e680-095e-11eb-84f3-94f7f59e4b71.png)

**Comment by rsargent** [comment]
Paul suggests check on level threshold for time machine layers

**Comment by pdille** [comment]
I would suggest breaking off the Landsat specific discussion from the initial issue raised here. They are different things.

**Comment by jjkohler** [comment]
Current issue is not the same as what was originally opened and has been opened separately in #159
