### ISSUE TITLE
Different layer/timeline behaviors depending on link used to access layer

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#139]
Also see #140 
Three different behaviors are shown for the same layer depending on how it is accessed.

1. When accessed at this link "Share only current view" style link:
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=4.56342,0,0,latLng&t=16.35&ps=100&l=h8_16&bt=20151101000000&et=20151130235000&startDwell=0&endDwell=0
No timeline displayed, but layer plays as expected.
![image](https://user-images.githubusercontent.com/42879120/94727265-76b5c380-032c-11eb-9e02-c2d318f8a165.png)

2. When accessed through the "start from current waypoint" link, layer displays no timeline and also fails to properly load images, sometimes stuttering between two frames, but never playing the whole sequence
https://staging.earthtime.org/stories/top_50#waypointIdx=18&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0
![image](https://user-images.githubusercontent.com/42879120/94727668-0eb3ad00-032d-11eb-9954-a0a30d7b514c.png)

3. While timeline active and visible when seen as part of a story and accessed by manually advancing to waypoint 18. (Correct and expected behavior for all three cases.)
https://staging.earthtime.org/stories/top_50#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0
![image](https://user-images.githubusercontent.com/42879120/94727385-a6fd6200-032c-11eb-87e6-4253f2667765.png)

**Comment by pdille** [comment]
I think these are all now working as they should. Please confirm.

**Comment by jjkohler** [comment]
@pdille cases 2 and 3 now seem to be resolved. For me, case 1 is now broken. Frozen on black screen but not playing, even though the button is selected in play position.
![image](https://user-images.githubusercontent.com/42879120/96052837-4ef64d80-0e4c-11eb-8e9d-53e2a66d01fb.png)

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-1.78111,0,-0.156,latLng&t=3.03&ps=50&l=h8_16&bt=20151101000000&et=20151130235000&startDwell=0&endDwell=0

This is the link generated by the system. Does this look as it should?

**Comment by pdille** [comment]
Please check these 3 cases again.
