### ISSUE TITLE
Markedly different zoom extents for waypoint accessed through Hash Link

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#141]
Similar to #139 and #140 this issue seems associated with share link behavior. The layer appears nearly the same between ET and Refactor when loaded within a story. When loaded from a waypoint specific share-link, the results in ET and Refactor are different from each other, and, in the case of Refactor, different internally when waypoint viewed within a story vs individually.

https://earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.44552,-79.96845,12.72,latLng&t=5&ps=50&l=bdrk_detailed,total_race_2010,bdrk,pgh_phh&bt=19600101&et=20191231&startDwell=0&endDwell=0
![image](https://user-images.githubusercontent.com/42879120/94734017-95b95300-0336-11eb-9410-02bf20d4809c.png)
Expected view as seen in ET and similar to view (apart from minor re-projection) seen in Refactor story.

Alternately, a far wider zoom extent is shown when accessing the waypoint directly in Refactor.
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.44552,-79.96845,12.72,latLng&t=5&ps=50&l=bdrk,bdrk_detailed,total_race_2010,pgh_phh&bt=19600101&et=20191231&startDwell=0&endDwell=0
![image](https://user-images.githubusercontent.com/42879120/94734186-df09a280-0336-11eb-9b15-eeb8d9b92816.png)

Interesting behavior to note:
When the link is loaded in ET, system first zooms to approximately the same view shown in Refactor, before jumping into tighter zoom right when the timeline loads. Refactor goes to the single (wider) zoom level, and then remains at this same extent as dots and other elements are loaded to the map. In general Refactor load behavior feels more pleasant than ET original behavior. But the inconsistences between zoom extents depending on how the waypoint is accessed needs addressed. 

Refactor link does NOT allow further zoom-in interaction on this map, making it impossible to even achieve the zoom extent seen in ET version of map.

**Comment by rsargent** [comment]
This is waypoint 20 on the top50

**Comment by pdille** [comment]
I believe this has been resolved, but please confirm.

**Comment by jjkohler** [comment]
All evidence suggests this has been corrected!

**Comment by rsargent** [comment]
Reopening as Harry and I are observing waypoint 36 (right after himawari 8) is doing this now:

![image](https://user-images.githubusercontent.com/324851/98965526-265b8500-24d8-11eb-8d2e-7b2256ee87db.png)

Note that this may be the same issue as https://github.com/CMU-CREATE-Lab/data-visualization-tools/issues/148

**Comment by rsargent** [comment]
Easy repro, put these two links in your chrome bookmark bar and click on then the other:

Waypoint 35
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-1.52666,0.56961,-0.156,latLng&t=0.5&ps=50&l=h8_16&bt=20151101000000&et=20151130235000&startDwell=0&endDwell=0

Waypoint 36
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.42128,-79.9361,10.25,latLng&t=0&ps=50&l=bdrk,bdrk_detailed,allegheny_county_pgh,popchange_black_1990_2010&bt=20151101000000&et=20151130235000&startDwell=0&endDwell=0

Click on 35 then 36

**Comment by pdille** [comment]
Should finally be fixed in commit 2a4bfacfb08 Please confirm!

**Comment by rsargent** [comment]
Super!  I can confirm it works for me on staging with with the bookmark bar repro.  @hjhawkinsiv please confirm next time the hal44 regression run completes :-).

**Comment by hjhawkinsiv** [comment]
This appears to be fixed as of the last test run.

**Comment by jjkohler** [comment]
Looks like we can re-close this now.
