### ISSUE TITLE
Vertical Pan Limits Need Expanded to full Mercator

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#142]
Current vertical pan limits are not set to full Mercator, meaning that global poles are not visible in relevant layers.

**Comment by rsargent** [comment]
https://staging.earthtime.org/explore#v=85,-5,2,latLng&l=blsat,h8_16 should be able to see the north pole of Himawari 8
https://staging.earthtime.org/explore#v=-85,-5,2,latLng&l=blsat,h8_16 should be able to see the south pole of Himawari 8

**Comment by rsargent** [comment]
Partial fix in e73b0c0547e30ee1de6d02fcb2a89373a8b64230
Remainder of fix should come from fixing #144

**Comment by pdille** [comment]
@rsargent Please confirm that the fix for #144 unblocks you.

**Comment by rsargent** [comment]
Paul and I confirmed, thanks Paul!
