### ISSUE TITLE
timelapse.viewportHeight seemingly doesn't match canvasLayer height

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#144]
When zooming out fully to fit full mercator exactly to the vertical bounds of the timelapse viewer, we get unexpected margins at top and bottom:

![image](https://user-images.githubusercontent.com/324851/94997990-d86c6c80-057c-11eb-941a-4a1d654973a8.png)

There seems to be a disagreement between the timelapse viewport height and the canvasLayer height, which in turn causes coordinate disagreements between timelapse.js and canvasLayer/webGL and blocks bug #142.

Zooming in a bit we can see the full vertical extents of the canvasLayer

![image](https://user-images.githubusercontent.com/324851/94998086-65afc100-057d-11eb-9e25-0062b0522e59.png)

Digging into the numbers, I think these two measures of the map height should match:

gEarthTime.timelapse.getViewportHeight()
585

gEarthTime.canvasLayer.canvas.clientHeight
635

To me the canvasLayer height looks correct.

**Comment by pdille** [comment]
Should be fixed commit 6981ed1 (which is a timemachine submodule fix)
