### ISSUE TITLE
Himawari 8 Imagery not loading 

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#145]
See also #132 

Staging
![image](https://user-images.githubusercontent.com/42879120/95487784-c61a7600-0962-11eb-8c69-e79c7fd45afe.png)
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-18.21224,0.56961,-3.203,latLng&t=2.99&ps=50&l=blsat&bt=19840101&et=20191231&startDwell=0&endDwell=0

Himawari 8 Imagery not loading

**Comment by pdille** [comment]
That share link doesn't have himawari8 layer encoded in it. Perhaps wrong link used here or the share link generating was invalid? I'm guessing what actually happened here was perhaps the share link was generated from waypoint 35? That would have created something like this. Either way, the issue related to waypoint 35 has been resolved.

**Comment by jjkohler** [comment]
Himawari 8 data all seems to now be showing correctly, with exception of #139 which is unrelated to this issue.
