### ISSUE TITLE
Needed: Stable pathway for accessing EXTRAS content by automated testing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#146]
Related to #128

**Comment by pdille** [comment]
@hjhawkinsiv  Do you need anything from me here now that extras are loading again on staging?

**Comment by jjkohler** [comment]
@hjhawkinsiv @pdille As of last report, extras are still not loading consistently in automated testing. It seems that this might be tied to memory cache over-runs in chrome? Any updates on this Harry?

**Comment by pdille** [comment]
@hjhawkinsiv Is this still relevant?

**Comment by jjkohler** [comment]
This issue has been addressed.
