### ISSUE TITLE
Timeline Style Difference

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#147]
2 Overview
12 Global Wind Power
15 Urban Fragility
22 Coral Reefs

**Comment by rsargent** [comment]
40 Temp Anomaly

**Comment by jjkohler** [comment]
14 City Lights

**Comment by gabrielo** [comment]
**2 Overview**
https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-12.92014,13.91479,0.024,latLng&t=1.6&ps=50&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-12.92014,13.91479,0.024,latLng&t=1.6&ps=50&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0

These look the same to me.

**Comment by gabrielo** [comment]
**12 Global Wind Power**
These should be the same now.

https://golden.earthtime.org/stories/top_50#waypointIdx=11&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

https://staging.earthtime.org/stories/top_50#waypointIdx=11&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by gabrielo** [comment]
**15 Urban Fragility**
These should be the same now.

https://golden.earthtime.org/stories/top_50#waypointIdx=14&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

https://staging.earthtime.org/stories/top_50#waypointIdx=14&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by gabrielo** [comment]
**22 Coral Reefs**
These should be the same now.

https://golden.earthtime.org/stories/top_50#waypointIdx=21&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

https://staging.earthtime.org/stories/top_50#waypointIdx=21&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by gabrielo** [comment]
**40 Temp Anomaly**
https://staging.earthtime.org/stories/top_50#waypointIdx=39&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0
Related to the way the timemachine and its timeline is being rendered. The timeline and the dates seem to be incorrect.

**Comment by gabrielo** [comment]
**14 City Lights**
https://staging.earthtime.org/stories/top_50#waypointIdx=13&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0
Related to the way timelines are being handled when dates are not specified.

**Comment by pdille** [comment]
14 and 40 should be resolved as of commit 808594a9be

**Comment by jjkohler** [comment]
> **2 Overview**
> https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-12.92014,13.91479,0.024,latLng&t=1.6&ps=50&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0
> https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-12.92014,13.91479,0.024,latLng&t=1.6&ps=50&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0
> 
> These look the same to me.

Confirmed.

**Comment by jjkohler** [comment]
Timelines appear to all be returned to proper style.
