### ISSUE TITLE
County moves layer (and others of same type) not drawing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#149]
Current:
![image](https://user-images.githubusercontent.com/42879120/95996801-141af800-0e01-11eb-857b-af455a36196b.png)

Expected:
![image](https://user-images.githubusercontent.com/42879120/95996833-1c733300-0e01-11eb-89cf-27bf976a1915.png)

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.42128,-79.9361,9.934,latLng&t=2.4&ps=50&l=bdrk,bdrk_detailed,allegheny_county_pgh,voting_ac_freq_num_moves_4_epoch&bt=20151101000000&et=20151130235000&startDwell=0&endDwell=0

(32 of Top 50)

**Comment by jjkohler** [comment]
almost certainly related to sitc layer functions from CSV sheet not working #163 

An accepted fix should fix these waypoints as well:
62 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.43348,-79.95612,12.483,latLng&t=0&ps=50&l=bdrk_detailed,allegheny_county_ownertype_epoch&bt=20100101&et=20171231&startDwell=0&endDwell=0
63 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.44516,-79.98502,9.52,latLng&t=0.7&ps=100&l=bdrk_subtle,allegheny_county_pgh,allegheny_county_outline,allegheny_school_district_outlines,voting_ac_freq_num_moves_4_epoch,voting_ac_freq_movers_4&bt=20050101&et=20191231&startDwell=0&endDwell=0
66 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.44552,-79.96845,12.72,latLng&t=0.07&ps=200&l=pgh_nhbds_2010,bdrk_detailed,allegheny_county_housing_bltyr_epoch&bt=20050101&et=20191231&startDwell=0&endDwell=0
87 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.43077,-80.02941,8.486,latLng&t=0&ps=200&l=bdrk,bdrk_detailed,voting_ac_us_house_boundaries_2018,voting_ac_num_moves_epoch&bt=20050101&et=20191231&startDwell=0&endDwell=0
96 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.46511,-80.00675,11.29,latLng&t=1.2&ps=200&l=bdrk_subtle,pgh_nhbds_2010,mortgages_ac_race_all_epoch&bt=20050101&et=20191231&startDwell=0&endDwell=0
97 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.46511,-80.00675,11.29,latLng&t=1.4&ps=200&l=bdrk_subtle,pgh_nhbds_2010,mortgages_ac_acceptance_status_all_epoch&bt=20050101&et=20191231&startDwell=0&endDwell=0
98 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.46511,-80.00675,11.29,latLng&t=1.2&ps=200&l=bdrk_subtle,pgh_nhbds_2010,mortgages_ac_acceptance_status_white_app_epoch&bt=20050101&et=20191231&startDwell=0&endDwell=0
99 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.46511,-80.00675,11.29,latLng&t=1.2&ps=200&l=bdrk_subtle,pgh_nhbds_2010,mortgages_ac_acceptance_status_black_app_epoch&bt=20050101&et=20191231&startDwell=0&endDwell=0
100 https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.45592,-80.01597,13.88,latLng&t=0.04&ps=50&l=bdrk_detailed,pgh_nhbds_2010,allegheny_county_saleprice_color_epoch_regular_sale_nonvacant_merged&bt=20050101&et=20191231&startDwell=0&endDwell=0

**Comment by gabrielo** [comment]
@jjkohler  This should be fixed with commit 952d876e37ec1fe569a08c947dd580ac05a30fb1

**Comment by jjkohler** [comment]
Brilliant! This is a huge one. SO many waypoints that were previously broken now working.
