### ISSUE TITLE
Refugee Flow Layer Incorrect

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#150]
Waypoint 2 of Top 50

Staging Golden significantly different in time. Staging appears to perhaps be some reversed version of time? e.g. circa 2011 refugees appear to flow INTO Syria from Turkey and elsewhere instead of out.

**Comment by gabrielo** [comment]
@jjkohler Could you provide sharelinks? Thx!

**Comment by jjkohler** [comment]
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=26.3011,35.85032,2.815,latLng&t=1.19&ps=100&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0

https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-12.92014,13.91479,0.024,latLng&t=1.6&ps=50&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0

**Comment by gabrielo** [comment]
@jjkohler The Google sheet had the wrong tile path defined. Sharelink behavior for the animated flow looks the same now. Please confirm and close.

**Comment by jjkohler** [comment]
Flows appear to be back to normal after fix by @gabrielo
