### ISSUE TITLE
Shared Tool can get stuck generating incorrect links

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#151]
Still working to isolate conditions in which this takes place.

Notice how same link is being generated regardless of which option is chosen:
![image](https://user-images.githubusercontent.com/42879120/95999595-0a46c400-0e04-11eb-96d1-a94bb5facf99.png)

![image](https://user-images.githubusercontent.com/42879120/95999650-192d7680-0e04-11eb-8720-6d45b1f99ff8.png)

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=26.3011,35.85032,2.815,latLng&t=1.19&ps=100&l=bdrk,ar&bt=20000101&et=20161231&startDwell=0&endDwell=0

**Comment by pdille** [comment]
This should be addressed in commit 179b18c407. Please confirm.

You should only be offered those specific share options when the waypoint slider is actually visible, otherwise they make no sense.

**Comment by jjkohler** [comment]
While this fix brought awareness to other smaller issues, this original issue has been fixed and will now be closed.
