### ISSUE TITLE
Different GOES 16 Views

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#152]
View in Golden
![image](https://user-images.githubusercontent.com/42879120/96004345-46c8ee80-0e09-11eb-8381-a64f1babf073.png)
https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=76.56346,-113.96152,4.821,latLng&t=60.93&ps=25&l=blsat,goes16-nov-2018&bt=20181101000036&et=20181130234535&startDwell=0&endDwell=0

View in Staging
![image](https://user-images.githubusercontent.com/42879120/96004361-4af50c00-0e09-11eb-8a78-ed2f808326bf.png)
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=76.56346,-113.96152,5.135,latLng&t=107.23&ps=25&l=blsat,goes16-nov-2018&bt=20181101000036&et=20181130234535&startDwell=0&endDwell=0

**Comment by pdille** [comment]
I'd be curious if we see something similar for Himawari links. I think so far all the Himawari ones in the top 50 are just full zoomed out?

**Comment by pdille** [comment]
It appears the problem is that golden let you zoom in further for GOES16 (and likely Himawari8 & DSCOVR). Not sure how we want to address that.

**Comment by pdille** [comment]
There is now an 'overZoom' constraint for a layer that allows a layer to zoom some percentage beyond its normal max zoom. GOES16 should now zoom to the desired zoom of this waypoint. @jjkohler  Please confirm in next automated test run.

**Comment by jjkohler** [comment]
Zoom level appears to be the same, but actual location center still appears to be different between Golden and Staging.

**Comment by jjkohler** [comment]
Accepting that new GOES 16 coordinates are likely more accurate than previous and closing as the zoom level issue seems to be fixed.
