### ISSUE TITLE
Deal with prioritizing basemaps to preserve old sharelink behavior

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#153]
Staging
![image](https://user-images.githubusercontent.com/42879120/96005562-8e03af00-0e0a-11eb-9473-067895771458.png)

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.4479,-79.94045,10.183,latLng&t=8.2&ps=50&l=bdrk_detailed,bdrk,pa_redlining_pgh_choropleth&bt=19360101&et=20201231&startDwell=0&endDwell=0

Golden
![image](https://user-images.githubusercontent.com/42879120/96005579-922fcc80-0e0a-11eb-8149-83a88531a0ba.png)

https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.45996,-79.94734,10.156,latLng&t=0&ps=50&l=bdrk_detailed,bdrk,pa_redlining_pgh_choropleth&bt=19360101&et=20201231&startDwell=0&endDwell=0

**Comment by rsargent** [comment]
Link contains both bdrk and bdrk_detailed;  need to prioritize bdrk_detailed by increasing draw order

**Comment by gabrielo** [comment]
@jjkohler 

Added **Draw Order** column to default spreadsheet and defined the value for _bdrk_detailed_ to be 110.

Appears to have fixed the problem.

Please confirm.

**Comment by rsargent** [comment]
Expanding this to "Deal with prioritizing basemaps to preserve old sharelink behavior".


Assign 100-199 in order to prioritize what's on top, according to the old drawing order from index.html and spreadsheet.

(index.ts should already have code to disable basemaps drawn below other basemaps.)

**Comment by gabrielo** [comment]
@jjkohler 

All layers categorized as **Base Maps** in the [Default spreadsheet](https://docs.google.com/spreadsheets/d/1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE/edit#gid=870361385) and the [Davos 2019 spreadsheet](https://docs.google.com/spreadsheets/d/1zbXFtyevXqfZolxVPNhojZn7y_zxofbe_4UxYmdXp8k/edit#gid=870361385) have had a Draw Order added that increases monotonically according to its position in the spreadsheet.

**Comment by pdille** [comment]
Should be fixed in 298e6470b9  Please confirm.

**Comment by jjkohler** [comment]
Based on the cases that I'm aware of, this fix seems to have "fixed" the issue. Current fix allows for bdrk_detailed to be shown above bdrk, even if it appears earlier in the sharelink than bdrk.
