### ISSUE TITLE
Timestamps look different possibly due to local/UTC time

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#154]
Waypoint 3 "Global Heat Signals":

![image](https://user-images.githubusercontent.com/324851/96006075-1c783080-0e0b-11eb-823a-b00bdcdf81a1.png)

Waypoint 18 "Jan 2015":
![image](https://user-images.githubusercontent.com/324851/96006168-33b71e00-0e0b-11eb-9f41-ec529840004a.png)

**Comment by gabrielo** [comment]
"Fires at Night" timelines now match.
https://staging.earthtime.org/stories/top_50#waypointIdx=2&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

https://golden.earthtime.org/stories/top_50#waypointIdx=2&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by gabrielo** [comment]
"Mediterranean refugees" timelines now match.
https://staging.earthtime.org/stories/top_50#waypointIdx=17&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

https://golden.earthtime.org/stories/top_50#waypointIdx=17&waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0

**Comment by jjkohler** [comment]
Layers seem to be fixed!
