### ISSUE TITLE
Difference in color/styling of coral reef layer

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#155]
22 of Top 50

Staging 
![image](https://user-images.githubusercontent.com/42879120/96006386-6d882480-0e0b-11eb-8082-792cd5daf603.png)
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=10.04219,124.64377,6.908,latLng&t=2.52&ps=50&l=blsat,coral_only,cb&bt=19840101&et=20161231&startDwell=0&endDwell=0

Golden
![image](https://user-images.githubusercontent.com/42879120/96006656-b7710a80-0e0b-11eb-9daf-3c0adecf33d0.png)
https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=9.91198,124.31699,7.044,latLng&t=4.8&ps=50&l=blsat,cb&bt=19360101&et=20201231&startDwell=0&endDwell=0

Less saturated color.
Was this an intended change?

**Comment by pdille** [comment]
I had added this layer back and likely didn't pick the exact same color. It's possible this was a specific shader before (which had a hardcoded color) but now we are using a generic line string shader which wants to know a color.

**Comment by gabrielo** [comment]
@jjkohler These should be an exact match. Please confirm and close if you agree.

**Comment by jjkohler** [comment]
@gabrielo The color seems to be the same now. There's still a difference in the drawing precision between the two layers. Staging version has less smooth lines (particularly visible on diagonal lines)
Staging:
![image](https://user-images.githubusercontent.com/42879120/96051901-7a783880-0e4a-11eb-964d-da7fa7f58116.png)

Golden:
![image](https://user-images.githubusercontent.com/42879120/96051939-87952780-0e4a-11eb-8826-19beac378c0e.png)

Is there a reason for this drawing difference?

**Comment by gabrielo** [comment]
There are a number of context differences between staging and golden.

**staging**
alpha: true
_**antialias: false**_
depth: true
desynchronized: false
failIfMajorPerformanceCaveat: false
powerPreference: "default"
premultipliedAlpha: true
preserveDrawingBuffer: false
_**stencil: true**_
xrCompatible: false

**golden**
alpha: true
_**antialias: true**_
depth: true
desynchronized: false
failIfMajorPerformanceCaveat: false
powerPreference: "default"
premultipliedAlpha: true
preserveDrawingBuffer: false
_**stencil: false**_
xrCompatible: false

Changing these context values for a WebGL context running on golden results in similar problems in the way the lines are drawn. Nite though I believe these new context values are required for the MapBox integration.

**Comment by jjkohler** [comment]
@gabrielo Thanks. I thinks this merits a discussion with the group.

**Comment by rsargent** [comment]
It looks like Mapbox layers should work fine with antialiasing turned on.
So I think we can turn it back on in index.ts and things will be back to
normal :-).

References:
https://github.com/mapbox/mapbox-gl-js/issues/7543
https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/

**Comment by gabrielo** [comment]
I'm not 100% sure that its the context differences. Doing some side-by-side comparisons.

**Comment by gabrielo** [comment]
@jjkohler original webgl context defaults restored with commit 0f5ff796737a2f313071b6e1e9770e0048dbfd8e.

Please confirm via 
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=10.24934,124.34322,9.834,latLng&t=0.83&ps=50&l=blsat,coral_only,cb&bt=19840101&et=20161231&startDwell=0&endDwell=0

https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=10.24934,124.34322,9.834,latLng&t=0.83&ps=50&l=blsat,cb&bt=19840101&et=20161231&startDwell=0&endDwell=0

**Comment by jjkohler** [comment]
Original behavior appears to have been restored
