### ISSUE TITLE
Sea Level Rise custom timeline style doesn't work

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#156]
Support for custom timeline in CSV layer regressed.

Waypoint 4: "Sea Level Rise"

![image](https://user-images.githubusercontent.com/324851/96009618-dcb34800-0e0e-11eb-8169-1142af827eeb.png)

**Comment by pdille** [comment]
This should now be working again. Please confirm. That said, we'll need a separate issue for getting the legend going.

**Comment by jjkohler** [comment]
Only the legend remains! This fixed a lot of layers in the next 50 as well.
