### ISSUE TITLE
Global Temperatures Continent/Country Titles Missing

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#157]
Golden:
![image](https://user-images.githubusercontent.com/42879120/96054178-13a94e00-0e4f-11eb-965f-b28d3c5562d5.png)
https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.41102,-0.9119,0.383,latLng&t=0&ps=100&l=blsat,land_borders_raster,berkeley-earth-temperature-anomaly&bt=185001&et=201703&startDwell=0&endDwell=0

Staging:
![image](https://user-images.githubusercontent.com/42879120/96054187-19069880-0e4f-11eb-8b70-c04770a993fa.png)
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.41102,-0.9119,0.383,latLng&t=0&ps=100&l=blsat,land_borders_raster,berkeley-earth-temperature-anomaly&bt=185001&et=201703&startDwell=0&endDwell=0

**Comment by pdille** [comment]
Should be fixed. Please confirm.

**Comment by jjkohler** [comment]
Behavior is now as expected.
