### ISSUE TITLE
Right Side of Screen Unexpectedly Purple

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#158]
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=5.53124,8.44479,0.208,latLng&t=13&ps=50&l=blsat,land_borders_raster,country_and_city_labels,berkeley-earth-temperature-anomaly-v2-yearly&bt=18500101&et=20181231&startDwell=0&endDwell=0

![image](https://user-images.githubusercontent.com/42879120/96054766-69322a80-0e50-11eb-8ad0-05a4b3a44dce.png)

This seems to have persisted from previously previously, but the right side of the screen in waypoint 8 Warming Planet is not black as would seem expected behavior and is instead purple.

Similar layer 27 Global Temperatures does not seem to have the same issue.
![image](https://user-images.githubusercontent.com/42879120/96054932-c928d100-0e50-11eb-94cc-4fd188239a81.png)

**Comment by pdille** [comment]
These are two different layers. V2 has that purple effect because of the colormap being applied, whereas the older one has the colors baked into the video tiles.

**Comment by pdille** [comment]
While the two being compared in this issue are indeed different layers, the good news is that purple is no more thanks to commit 198a1d56

Credit to @rsargent for this!

**Comment by jjkohler** [comment]
sigh. I will now sleep better at night.
