### ISSUE TITLE
Fire size may be larger on RTFL

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#160]
Need to check on this:

![image](https://user-images.githubusercontent.com/324851/96152861-ffab2e00-0eda-11eb-85e2-510e00231a37.png)

Might instead be a time offset?

**Comment by gabrielo** [comment]
Discussed during today's meeting as a possible result of webgl context differences between staging and golden. This is **not** the case.

Currently the **refactor** branch uses _gEarthTime.gmapsZoomLevel()_ to calculate _pointSize_ but should use _gEarthTime.timelapseZoom()_  to mimic what's deployed on **golden**.

This problem affects a few other visualizations as well. I will compile a list of what looks like its affected from the **Top 50** waypoints.

**Comment by gabrielo** [comment]
**VIIRs**
https://staging.earthtime.org/explore#v=24.27665,5.605,0.69,latLng&t=20.88&ps=100&l=bdrk,viirs&startDwell=0&bt=20140917&et=20171009&redo=2
https://golden.earthtime.org/explore#v=24.27665,5.605,0.69,latLng&t=20.88&ps=100&l=bdrk,viirs&startDwell=0&bt=20140917&et=20171009&redo=2

**7 Tuareg rebellion**
https://staging.earthtime.org/explore#v=17.25395,0.25593,5.248,latLng&t=1.57&ps=50&l=bdrk,acled_all_event_types&bt=20120101&et=20181231&startDwell=0&endDwell=1.0&forceLegend=true
https://golden.earthtime.org/explore#v=17.25395,0.25593,5.248,latLng&t=1.57&ps=50&l=bdrk,acled_all_event_types&bt=20120101&et=20181231&startDwell=0&endDwell=1.0&forceLegend=true

**12 Global Wind Power**
https://staging.earthtime.org/explore#v=42.06872,-1.70588,0.205,latLng&t=3.25&l=bdrk,gwp&ps=25&bt=19840101&et=20181231&startDwell=0&endDwell=1.0
https://golden.earthtime.org/explore#v=42.06872,-1.70588,0.205,latLng&t=3.25&l=bdrk,gwp&ps=25&bt=19840101&et=20181231&startDwell=0&endDwell=1.0

**22 Coral Reefs**
https://staging.earthtime.org/explore#v=3.13745,21.28147,0.349,latLng&t=3.24&ps=0&l=blsat,cb&bt=19840101&et=20161231&disableUI=true
https://golden.earthtime.org/explore#v=3.13745,21.28147,0.349,latLng&t=3.24&ps=0&l=blsat,cb&bt=19840101&et=20161231&disableUI=true

**72 Solar PV**
https://staging.earthtime.org/explore#v=39.68237,-97.4215,2.248,latLng&t=0.38&startDwell=0&endDwell=1.0ps&l=bdrk,sp&bt=19840101&et=20161231&ps=25
https://golden.earthtime.org/explore#v=39.68237,-97.4215,2.248,latLng&t=0.38&startDwell=0&endDwell=1.0ps&l=bdrk,sp&bt=19840101&et=20161231&ps=25

**88 Context**
https://staging.earthtime.org/explore#v=13.97115,10.14732,3.257,latLng&t=0.42&ps=50&l=bdrk,acled_v1&bt=19970101&et=20181231&startDwell=0&endDwell=1.5
https://golden.earthtime.org/explore#v=13.97115,10.14732,3.257,latLng&t=0.42&ps=50&l=bdrk,acled_v1&bt=19970101&et=20181231&startDwell=0&endDwell=1.5

**Comment by gabrielo** [comment]
golden and staging should match for the above examples as of commit e654016bb394eb70b75c18f79cb8d5f8f9a339cb

**Comment by jjkohler** [comment]
@gabrielo I'm still seeing significant size differences between golden and staging. Has this fix been fully implemented yet?

Golden
![image](https://user-images.githubusercontent.com/42879120/96920039-a4e57980-147a-11eb-83b8-136563bf64c8.png)

Staging
![image](https://user-images.githubusercontent.com/42879120/96919913-78c9f880-147a-11eb-8f63-24bfd5ce1afa.png)

**Comment by gabrielo** [comment]
@jjkohler staging wasn't update to date.

![image](https://user-images.githubusercontent.com/213242/96993561-7a86d100-14f9-11eb-9eac-e1259e42de6d.png)

![image](https://user-images.githubusercontent.com/213242/96993642-95f1dc00-14f9-11eb-8776-56f24a34e6dd.png)

**Comment by jjkohler** [comment]
Thanks for the update! Sizes appear to be matching.
