### ISSUE TITLE
Layer Missing Legend

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#161]
Golden:
![image](https://user-images.githubusercontent.com/42879120/96641895-607ba180-12f3-11eb-8a31-8263f9534984.png)

Staging:
![image](https://user-images.githubusercontent.com/42879120/96641865-56f23980-12f3-11eb-95b8-2bd931804959.png)

https://staging.earthtime.org/explore#v=164614,315576,2038850,1369833,pts&t=0.1&ps=0&l=bdrk,global_gender_gap_index_10_year_change_aberkley&bt=0.1&et=0.1&startDwell=0&endDwell=0&fps=30

@gabrielo I think maybe you've already worked with this layer?

**Comment by gabrielo** [comment]
commit 21e3da4971ed471bbd6bd4430fbba53135d2b056

Should be resolved. Auto generated legends for choropleth maps were failing.

**Comment by jjkohler** [comment]
Seems to be working!
