### ISSUE TITLE
Ram usage increases unsustainably as more and more layers are shown

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#162]
When testing in Chrome the top 100, at some point RAM usage goes beyond 60GB -- not sure which waypoint.  It seems likely that we need to intentionally unload tiles for layers that aren't shown, or remove layers altogether from LayerDB, using LRU.

Main branch has the ability to LRU unload tiles;  this is a regression for RTFL

**Comment by jjkohler** [comment]
This can be closed soon hopefully once Harry gets to do a little more work with automated testing.

**Comment by jjkohler** [comment]
So far it seems that this has been implemented successfully. Can re-open if issues still seem to remain.
