### ISSUE TITLE
Dot Flow Maps Not Functioning

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#166]
54
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-0.64935,13.89178,0.789,latLng&t=1.15&ps=50&l=bdrk,oecd_oda_sahel&bt=19550101&et=20301231&startDwell=0&endDwell=0

76
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=18.78224,3.18397,0.881,latLng&t=1.2&ps=50&l=bdrk,sitc4r2_commodities_8&bt=19550101&et=20301231&startDwell=0&endDwell=0

A full solution likely related to **sitc layer functions from CSV sheet not working** #163

**Comment by gabrielo** [comment]
@jjkohler  Dots flow maps should be flowing again.

**Comment by jjkohler** [comment]
Looks like a successful solution to this issue!
