### ISSUE TITLE
Lower Hill Historical Images not loading

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#167]
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.44217,-79.99072,14.5,latLng&t=0&ps=50&l=bdrk_detailed&bt=0.03&et=2.03&startDwell=0&endDwell=0

**Comment by pdille** [comment]
We previously had this code to change the projection for this layer:
```
var view = timelapse.getView();

var p = timelapse.getProjection();
var offset = p.latlngToPoint({
  "lat": 40.44945971297983,
  "lng": -80.00253546388332
});

var longEast = -79.97771966607753;
var longWest = -80.00253546388332;
var timelapse2map = (lowerHillTimemachineLayer.getWidth()/(longEast-longWest)) / (landsatBaseMapLayer.getWidth()/360);
view.scale /= timelapse2map;

view.x = timelapse2map * (view.x - offset.x);
view.y = timelapse2map * (view.y - offset.y);

lowerHillTimemachineLayer.draw(view, tileViewVisibility);
```

**Comment by pdille** [comment]
Should be fixed in commit 98b98c8d5457 Please confirm.

Credit to @rsargent for this!

**Comment by rsargent** [comment]
Paul and I also managed to crop out the tile margin from display by
changing vertex and texture coords.  This removes the large margins on the
right and bottom, which were impacting the Hill video and temp anomaly
video, and perhaps more.

**Comment by jjkohler** [comment]
Since frame skipping is beyond the scope of this issue, we'll close it and consider revisiting the frame issue at a later point.
