### ISSUE TITLE
Different Timeline Increments/Basemap for GDP Layer

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#168]
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-16.10428,-20.18342,1.983,latLng&t=2.53&ps=25&l=blsat,gdpPpp&bt=19700101000000&et=19700101000000&startDwell=0&endDwell=0
![image](https://user-images.githubusercontent.com/42879120/97444977-1c942800-1903-11eb-8bfc-aaeac6b2c1ba.png)

https://golden.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-16.10428,-20.18342,1.985,latLng&t=1.43&ps=25&l=blsat,gdpPpp&bt=19900101&et=20151231&startDwell=0&endDwell=0
![image](https://user-images.githubusercontent.com/42879120/97444878-01291d00-1903-11eb-953d-182eee4715e3.png)

Both have blsat as the base layer, but it is displaying in staging while invisible in golden. Correct behavior should be chosen.

**Comment by pdille** [comment]
Timeline fixed. Dates were wrong in the timemachine definition.

As for the base layer discrepancy... I believe this is the result of previously limiting to just one timemachine drawn at once. That performance issue still exists, but in regards to both being drawn now, that is the correct general layer behavior. Whether we want to limit timemachine drawing is up for debate I suppose, but I lean towards this being on the user to choose the layers and if too many are chosen, that's on the user.

**Comment by jjkohler** [comment]
This specific case has been solved, so unless further discussion is needed, closing this issue.
