### ISSUE TITLE
"Undefined" appearing in legend

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#170]
![image](https://user-images.githubusercontent.com/42879120/98132199-1c0f0a80-1e8a-11eb-8deb-6492c9816e49.png)

https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=-0.64935,13.89178,0.789,latLng&t=1.15&ps=50&l=bdrk,oecd_oda_sahel&bt=19550101&et=20301231&startDwell=0&endDwell=0

**Comment by pdille** [comment]
Should be fixed in commit eeb4fac Please confirm.

**Comment by jjkohler** [comment]
Does indeed seem fixed.
