### ISSUE TITLE
LayerFactory needs to set default drawing order according to design

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#173]
Waypoint 71 shows bubbles below dots, and it looks wrong:
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.4571,-79.92758,10.188,latLng&t=2.03&ps=50&l=bdrk_detailed,bdrk,allegheny_county_pgh,coop_bubbles,anim_total_race_1990_2010&bt=19900101&et=20101231&startDwell=0&endDwell=0

![image](https://user-images.githubusercontent.com/324851/98830141-0c527180-2408-11eb-8a86-ddffcbf52df5.png)

Current drawing order strategy is to put bubbles above dots:
https://docs.google.com/document/d/1uesUk8OaWr4yQAXfuvgVMJGEY0Cr9q3gCrFy6sfqOxg/edit#heading=h.9nqhct833xb1

Should we change this?

**Comment by rsargent** [comment]
Expanding this bug to include all defaults to be set in LayerFactory

**Comment by jjkohler** [comment]
@rsargent can this now be closed with the work you did this last weekend?

**Comment by rsargent** [comment]
Yes, confirmed!
