### ISSUE TITLE
Explore Button on Landing Page Broken for Staging

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#174]
![image](https://user-images.githubusercontent.com/42879120/99714536-b3bc4d80-2a73-11eb-9d4d-2238e31691c0.png)

Clicking the "Explore Earthtime" button on the main ET page produces no result.

**Comment by pdille** [comment]
Yeah, something happened in a recent timemachine submodule update. I'll take a gander...

**Comment by jjkohler** [comment]
In relation to this issue, the page is further broken, not putting images into albums, etc.

**Comment by pdille** [comment]
Should be fixed in 1f60055. Please confirm. @jjkohler

**Comment by jjkohler** [comment]
A terrifying number of (some broken) stories still try to load on the main page - which I believe should be fixed seperately, but the actual thing that this issue was about has been fixed, so time to close this.
