### ISSUE TITLE
Charts Not Functional

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#175]
Example:

https://staging.earthtime.org/explore#v=39.04721,117.38574,3.598,latLng&t=1.04&ps=25&l=bdrk,air_visual_beijing_annual_pm25,air_visual_beijing_annual_pm25_chart&bt=20080101&et=20181231
![image](https://user-images.githubusercontent.com/42879120/99715360-bf5c4400-2a74-11eb-87f9-b9e052312af2.png)

https://golden.earthtime.org/explore#v=39.04721,117.38574,3.598,latLng&t=1.04&ps=25&l=bdrk,air_visual_beijing_annual_pm25,air_visual_beijing_annual_pm25_chart&bt=20080101&et=20181231
![image](https://user-images.githubusercontent.com/42879120/99715442-e286f380-2a74-11eb-980a-3761168137dc.png)

**Comment by pdille** [comment]
Should be resolved in commit 0deac7a

Please confirm.

**Comment by jjkohler** [comment]
This looks great!
