### ISSUE TITLE
EXTRA layers frozen when accessed manually 

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#177]
Turning on an EXTRA layer from the library manually produces incorrect behaviors. This includes:

Extra layer can not be toggled on/off.
It can only be cleared by either "Clear Active Layers" or closing with the X in the corner.
Once clearing or closing, the layer can not be activated again until site is reloaded.

Example Image:
Note that layer has been unchecked, but still persists
![image](https://user-images.githubusercontent.com/42879120/99718967-b15cf200-2a79-11eb-86c3-808b265c7a64.png)

**Comment by pdille** [comment]
Should be fixed in commit 83336c46 Please confirm

**Comment by pdille** [comment]
Further tweak in commit 1121c979 @jjkohler as we discussed, double check this.

**Comment by jjkohler** [comment]
This now appears to be fixed!
