### ISSUE TITLE
Plume layers throw a shader error on initialization

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/data-visualization-tools#178]
Current: https://staging.earthtime.org/explore#v=40.38189,-79.87507,9.974,latLng&t=27.73&ps=50&l=blte,plume_20190301&bt=201905100400&et=201905200350&startDwell=0&endDwell=0

Expected:
https://golden.earthtime.org/explore#v=40.38189,-79.87507,9.974,latLng&t=27.73&ps=50&l=blte,plume_20190301&bt=201905100400&et=201905200350&startDwell=0&endDwell=0

Note: This layer takes a long time to load, which is to be expected.

Error given on staging:
> Uncaught (in promise) Error: Cannot find shader function "WebGLVectorTile2.particleAltFadeVertexShader"
    at Function.getShader (LayerFactory.ts:970)
    at overrideDrawingFns (LayerFactory.ts:251)
    at LayerFactory.createLayer (LayerFactory.ts:326)
    at LayerProxy._loadFromLayerdef (LayerProxy.ts:93)
    at LayerProxy._load (LayerProxy.ts:84)

**Comment by gabrielo** [comment]
golden fails for me as well with the following in console:
![image](https://user-images.githubusercontent.com/213242/100926469-816a1180-34b1-11eb-8e2e-78f2dff3b950.png)

**Comment by gabrielo** [comment]
@pdille @jjkohler 
Further the shaders specified **_WebGLVectorTile2.particleAltFadeVertexShader_** and **_WebGLVectorTile2.particleAltFadeFragmentShader_** do not appear to be in the source code of the master branch as actual shaders. See https://github.com/CMU-CREATE-Lab/data-visualization-tools/blob/master/examples/webgl-timemachine/WebGLVectorTile2.js

Do you have an example of a (sub)domain where these work?

**Comment by gabrielo** [comment]
@jjkohler 
Shaders added to refactor branch with commit eb119e7e90e59bcc94b25c112da23c27b8f4d777.

Note this never worked on golden only on headless-rsargent.

**Comment by jjkohler** [comment]
This appears to have been fixed.
