### ISSUE TITLE
Plume layer altitude slider is missing

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/data-visualization-tools#180]
Related to #178 but likely independent of the shader loading issue found there. 

The problem for this is most likely the UI is no longer being loaded.

**Comment by rsargent** [comment]
Also check on hardcoded altitude in the shader

**Comment by rsargent** [comment]
Let's move to adjusting this in the layer definition instead;  closing this as no longer needed for now.  Feel free to reopen if you need the feature.
