### ISSUE TITLE
Clear Active Layer button behavior incorrect

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#181]
"Clear Active Layer" button present even if no layers are active.

This produces particularly odd results as it allows repeat clicking. The results are odd, opening and closing seemingly random categories. Disabling the button at the correct point should get rid of these behaviors

Plot twist: Nothing is active to be cleared
![image](https://user-images.githubusercontent.com/42879120/99720994-87f19580-2a7c-11eb-95e2-8f8b8a0c228e.png)

**Comment by pdille** [comment]
Should be fixed in commit 83336c46 Please confirm.

**Comment by jjkohler** [comment]
Clear active layers functionality seems to have been restored.
