### ISSUE TITLE
Add back indicator to a category (black circle) that a layer is enabled under it

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#182]
Expected behavior
![image](https://user-images.githubusercontent.com/42879120/99721336-0b12eb80-2a7d-11eb-8163-414144c5a16a.png)

Current Staging Behavior
![image](https://user-images.githubusercontent.com/42879120/99721605-7b217180-2a7d-11eb-8380-5c985668630b.png)

**Comment by pdille** [comment]
Fixed in commit 9b45597d  Please confirm @jjkohler

**Comment by jjkohler** [comment]
Correct behavior appears to have been restored.
