### ISSUE TITLE
Needed: Logic to make basemaps not control timeline when paired with other layer

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#183]
See examples below

**Comment by rsargent** [comment]
Normally, the last selected layer (rightmost in the share link) controls the timeline.  But layers without timelines don't affect this.

Proposed behavior #3: Layers with single timestamp (begin time = end time) show a year without a timeline.  And enforce that animated base layers like landsat pause that at same time.

Proposed behavior #1:  Base map timeline always has lower priority than other layer's timeline, even if the base map is later in the share link.

#2: If overlay layer has a single time (begin time = end time) e.g. Cropland Extents 2015, display that year by the timeline but without an actual timeline bar+scrubber.  This should override basemap timeline too like #1, and would seek the basemap to the closest time representable (e.g. layer is 2000 shows landsat 2000, or layer is 1950 shows landsat 1984).

#3.  For Forest loss by year 2000-2018 atop landsat, show landsat 2018 and no year at the bottom.

**Comment by gabrielo** [comment]
Testing URLs
**1**  _Base map timeline always has lower priority than other layer's timeline, even if the base map is later in the share link._
https://staging.earthtime.org/explore#v=4.56342,0,0,latLng&t=2.66&ps=50&l=pure_earth_modern_pollution,bdrk&bt=19900101&et=20161231&startDwell=0&endDwell=0

**2** _Layers with single timestamp (begin time = end time) show a year without a timeline. And enforce that animated base layers like landsat pause that at same time._
https://staging.earthtime.org/explore#v=54.9517,-4.52115,4.594,latLng&t=3.57&ps=50&l=uk_eu_referendum_2016,blsat&bt=19840101&et=20191231&startDwell=0&endDwell=0

**Comment by gabrielo** [comment]
Logic added with commit 145bf078fb546c4eea8edcf0156b25430c1e3f37

Displaying single year and or span of years requires further development.

**Comment by gabrielo** [comment]
If data visualization layer has a single time (begin time = end time) e.g. Cropland Extents 2015, display that year by the timeline but without an actual timeline bar+scrubber.
https://github.com/CMU-CREATE-Lab/data-visualization-tools/issues/194

**Comment by gabrielo** [comment]
More tests.

**A data layer timeline should take precedence over the landsat base map, even if the landsat base map is later in the share link.**
- A layer with a single year specified on top of landsat should show no timeline and landsat should be paused to that year.
https://staging.earthtime.org/explore#v=55.76294,-4.07193,3.873,latLng&t=0.04&ps=50&l=blsat,uk_eu_referendum_2016&bt=20160101&et=20161231&startDwell=0&endDwell=0
https://staging.earthtime.org/explore#v=55.76294,-4.07193,3.873,latLng&t=0.04&ps=50&l=uk_eu_referendum_2016,blsat&bt=20160101&et=20161231&startDwell=0&endDwell=0 

- A layer with a range of years and a timeline different from landsat should show that layer's timeline.
https://staging.earthtime.org/explore#v=4.56342,0,0,latLng&t=11.13&ps=50&l=blsat,gm_co2&bt=19000101&et=20111231&startDwell=0&endDwell=0
https://staging.earthtime.org/explore#v=4.56342,0,0,latLng&t=11.13&ps=50&l=gm_co2,blsat&bt=19000101&et=20111231&startDwell=0&endDwell=0

- A layer with a range of years and no timeline different from landsat should show no timeline.
https://staging.earthtime.org/explore#v=4.56342,0,0.994,latLng&t=3.03&ps=50&l=blsat,vsi&bt=19840101&et=20191231&startDwell=0&endDwell=0
https://staging.earthtime.org/explore#v=4.56342,0,0.994,latLng&t=3.03&ps=50&l=vsi,blsat&bt=19840101&et=20191231&startDwell=0&endDwell=0

**Comment by jjkohler** [comment]
For further discussion, probably in next week's ET meeting with @pdille @rsargent @gabrielo 

Forest Loss by Year
https://staging.earthtime.org/explore#v=-6.89408,-12.59708,0.921,latLng&t=3.43&ps=50&l=blsat,fly&bt=19840101&et=20191231&startDwell=0&endDwell=0

Croplands
https://staging.earthtime.org/explore#v=34.78126,-86.01422,4.299,latLng&t=3.57&ps=50&l=blsat,cropland&bt=19840101&et=20191231&startDwell=0&endDwell=0

Landsat Advancing only through the 1930s and then stopping
https://staging.earthtime.org/explore#v=34.27548,-109.4899,5.912,latLng&t=6.75&ps=50&l=blsat,gm_co2&bt=19000101&et=20111231&startDwell=0&endDwell=0
These tie closely to #184

**Comment by jjkohler** [comment]
I believe that all the documented cases related to this issue have now been solved. Pending any further issues being identified, this issue can be closed.
