### ISSUE TITLE
Public regressions where overlays are defined over time range that does not properly align with landsat

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#184]
When land sat is turned on with data for a time frame beyond the last year of satellite imagery (e.g. 2020), it continues to advance, using time increments arbitrarily to advance through different years of data. This can be seen at the above link.

**Comment by rsargent** [comment]
I can fix by adding another special-case naming the layer in WebGLVideoTile.ts, but the better approach would be to fix the code to take advantage of the new timeline metadata to make a more principled adaptation between the timeline, its rate of playback, and its range compared to the TimeMachineLayer.

I'd much prefer the second approach, but it's somewhat involved and will require a lot of testing.  Could we rationalize delaying this until after release?  Are there important regressions in behavior for stories and layers that are in use?

**Comment by jjkohler** [comment]
https://staging.earthtime.org/explore#v=53.54278,-88.87661,2.246,latLng&t=2.24&ps=100&l=2019_nCOV_infection_confirmed_cases_bubble_no_legend,blsat&bt=20200120&et=20201230&startDwell=0&endDwell=0

@rsargent Here's an example of this issue, paired with a publicly available layer. During the first weeks of 2020 data, the landsat layer actively cycles through years worth of data, before freezing at some point.

**Comment by jjkohler** [comment]
@rsargent another example of mismatch between landsat and an overlaying data layer: https://staging.earthtime.org/explore#v=36.14414,-115.17283,10.201,latLng&t=1.55&ps=50&l=blsat,uf&bt=20000101&et=20151231&startDwell=0&endDwell=0

**Comment by jjkohler** [comment]
https://staging.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&v=40.45977,-79.9213,11.075,latLng&t=0.46&ps=50&l=blsat,us_redlining_all_A_outlines_b,us_redlining_all_B_outlines_b,us_redlining_all_C_outlines_b,us_redlining_all_D_outlines_b,anim_total_race_1990_2010,pgh_hud_subsidized&bt=19600101&et=20211231&startDwell=0&endDwell=0

Another example of the data layer gratuitously advancing landsat, for years that landsat imagery is not actually present.

**Comment by jjkohler** [comment]
Landsat Advancing only through the 1930s and then stopping
https://staging.earthtime.org/explore#v=34.27548,-109.4899,5.912,latLng&t=6.75&ps=50&l=blsat,gm_co2&bt=19000101&et=20111231&startDwell=0&endDwell=0

**Comment by rsargent** [comment]
Should be fixed with e00ff3ef7783d07bd93f08f64187fffba7af24ee.  Jared, would you be willing to check?

**Comment by rsargent** [comment]
Fixed regression with 8980e7de8f1ca9669a6e757ee036c968934bdc1c

@jjkohler please check again?

**Comment by jjkohler** [comment]
It appears that this fix now addresses all the known cases.
