### ISSUE TITLE
Add back icon for layer description (from markdown in the layer def spreadsheet)

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#185]
Expected Behavior
![image](https://user-images.githubusercontent.com/42879120/99724713-056bd480-2a82-11eb-909c-ab3808128a7b.png)

Staging Behavior
![image](https://user-images.githubusercontent.com/42879120/99724837-377d3680-2a82-11eb-99f0-b36832c20bc2.png)

It is possible that the question marks will be replaced with an (i) instead of the (?)

**Comment by jjkohler** [comment]
Determined to be duplicated by #202 so that issue was close while this one left open

**Comment by pdille** [comment]
@gabrielo 

Right now the only way to get the layer description info is to do a request of a full layer and get back all the information about it.

Could we add a new api request to return just the description? 

Right now to get a layer we do:

https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.74523005/layers/blsat

Perhaps a proposed way to get just a layer description would be:

https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.74523005/layers/blsat/description

**Comment by gabrielo** [comment]
@pdille 
[https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.74523005/layers/blsat/layer_description](https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.74523005/layers/blsat/layer_description)

**Comment by pdille** [comment]
Awesome, many thanks!!

I'm gonna be that guy though and bring up the fact that we have both "-" and "_" in the API now. 

"layer-catalogs"
"layer_description"

I also believe nearly all layer ids make use of "_" but that itself is its [own topic](https://github.com/CMU-CREATE-Lab/data-visualization-tools/issues/105).

Could we standardize on one for the db API?

**Comment by gabrielo** [comment]
@pdille  Excellent point.

API uses a "-" now instead of "_".
[https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.74523005/layers/blsat/layer-description](https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.74523005/layers/blsat/layer-description)

**Comment by jjkohler** [comment]
This functionality has now been restored. Nay, (i)improved!
