### ISSUE TITLE
Default Base Layers Not Loading along with data layers

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#186]
When manually loading layers from the Data Library in Staging, default base layers are not loaded or honored. This allows for loading of most layers without any background, unless a user manually activates a base layer from the menu.

**Comment by rsargent** [comment]
(The spreadsheet currently specifies a desired basemap for each layer, and it's not being honored.)

**Comment by rsargent** [comment]
I just added a Base layer column to the dotmaps sheet tab and populated with "bdrk_subtle", so census dotmap layers are correctly reporting Base layer from api.earthtime.org. @pdille @gabrielo @arwright @jjkohler @hjhawkinsiv

**Comment by pdille** [comment]
Should be addressed in commit af3bd39c

@jjkohler @hjhawkinsiv As discussed, re-implementing this could have caused regressions. Please test this rigorously in your test suite.

**Comment by rsargent** [comment]
This seems to be a regression, but I'm not confident of the intended behavior so let me know if I'm misunderstanding

Layers l=blsat,uf

golden shows Urban Fragility atop landsat
https://golden.earthtime.org/explore#v=36.14414,-115.17283,10.201,latLng&l=blsat,uf
![image](https://user-images.githubusercontent.com/324851/105985985-424bdd00-606a-11eb-9bfa-3cede0f33cc7.png)

staging shows Urban Fragility atop dark map:
https://staging.earthtime.org/explore#v=36.14414,-115.17283,10.201,latLng&l=blsat,uf
![image](https://user-images.githubusercontent.com/324851/105986085-68717d00-606a-11eb-9898-dd8aa07b7a40.png)

**Comment by pdille** [comment]
More changes in commit ba128379

Per the discussion, paired base maps should only show if the user is manually turning them on and not when part of a share link. 

Please run through the tests again! Thanks.

**Comment by jjkohler** [comment]
Testing indicates that this issue has been fixed.
