### ISSUE TITLE
Change dot flows (e.g. refugees, crude flows) in layers spreadsheet to Draw Order 700

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#188]
More info in #187

**Comment by rsargent** [comment]
Need to override draw order to 700 in spreadsheet for refugee and crude flows (and other flows) as the default assigned is 600, but the design intent is draw level 700.

**Comment by rsargent** [comment]
To clarify, there aren't known examples where this shows a regression.  It's simply that it might cause future confusion if these layers don't match the design spec.

**Comment by pdille** [comment]
@gabrielo While not a critical for release, would you be willing to go through the Sheets and set the draw order value for the types of layers mentioned above? I think you know best what flow layers we have and it would be good to bring closure to the draw order related topics.

**Comment by pdille** [comment]
@gabrielo 

I was running into an issue with draw order for a point-flow type layer, so I went ahead and made the draw order changed discussed here. I modified layers that had the following draw functions. Did I miss any other flow type layers?

_drawPointFlow,
_drawSitc4r2, 
_drawAnnualRefugees, 
_drawMonthlyRefugees, 
_drawSpCrude

**Comment by gabrielo** [comment]
@pdille 

I think just the layers using the **__drawParticles_** which I've updated to now as well.

**Comment by jjkohler** [comment]
This should be ready to close now.
