### ISSUE TITLE
Square Points Not loading Properly

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#198]
https://staging.earthtime.org/explore#v=26.17623,81.10622,4.053,latLng&t=0&ps=0&l=unu_modern_slavery_india_kilns,blsat&bt=0&et=0&startDwell=0&endDwell=0&fps=30
![image](https://user-images.githubusercontent.com/42879120/102798004-7bfc3a80-437e-11eb-980b-aae0e690eb08.png)

unu_modern_slavery_india_kilns layer does not load.

This shader missing error shows in dev console:

LayerFactory.ts:1038 Uncaught (in promise) Error: Cannot find shader function "WebGLVectorTile2.basicSquareFragmentShader "
    at Function.getShader (LayerFactory.ts:1038)
    at overrideDrawingFns (LayerFactory.ts:280)
    at LayerFactory.createLayer (LayerFactory.ts:344)
    at LayerProxy._loadFromLayerdef (LayerProxy.ts:100)
    at LayerProxy._load (LayerProxy.ts:91)

Expected View from golden:
![image](https://user-images.githubusercontent.com/42879120/102798034-8a4a5680-437e-11eb-98f4-373359118a7a.png)
https://golden.earthtime.org/explore#v=26.17623,81.10622,4.053,latLng&t=0&ps=0&l=unu_modern_slavery_india_kilns,blsat&bt=0&et=0&startDwell=0&endDwell=0&fps=30

**Comment by gabrielo** [comment]
@jjkohler Fixed.

**Comment by jjkohler** [comment]
confirmed!
