### ISSUE TITLE
Move dotmap layer descriptions from 'CSV Layers' to 'Dotmap Layers'

### ISSUE THREAD

**Issue by hjhawkinsiv** [CMU-CREATE-Lab/data-visualization-tools#199]
The 'CSV Layers' sheet contains the layer descriptions for dotmaps. Current behavior is that the information of these layers are either overwritten or the description is ignored.

See rows 1932-1960 in 'CSV Layers' of default sheet.

**Comment by rsargent** [comment]
I removed these from CSV layers tab and added to Dotmap layers tab.

I confirmed api.earthtime.org correctly reports layer description for total_race_1990:

https://api.earthtime.org/layer-catalogs/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.1677314377/layers/total_race_1990
yields
![image](https://user-images.githubusercontent.com/324851/104009030-5fcb0c80-5178-11eb-9389-a1df1e07a461.png)

(The info icon won't display though in Data Library yet until we fix #202)
