### ISSUE TITLE
ps=XX not honored when visiting sharelink

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#200]
ps=XX appears not to be honored when visiting sharelink (but is honored when clicking on a story waypoint)

Originally reported in #192 

Waypoint 72:

![image](https://user-images.githubusercontent.com/324851/103786237-355b4100-500a-11eb-833d-ef9fabfc3cfb.png)

When clicking on waypoint 72 in golden vs staging, both show up as "Slow" by default and have same speeds.

Regression testing seems to instead show Medium speed for staging, as does following the regression testing link
![image](https://user-images.githubusercontent.com/324851/103786783-d2b67500-500a-11eb-881e-74674007c96d.png)

The link that shows medium in staging has ps=25, which should be slow, but produces medium in staging.  (Similar link correctly produces slow in golden)

https://staging.earthtime.org/explore#v=39.68237,-97.4215,2.248,latLng&t=0.38&startDwell=0&endDwell=1.0ps&l=bdrk,sp&bt=19840101&et=20161231&ps=25

------------

Waypoint 206 is due to ps=XX not being honored

https://golden.earthtime.org/explore#v=40.4479,-79.94045,10.5,latLng&t=5&ps=15&l=bdrk,bdrk_detailed,allegheny_county_pgh,anim_acs_poverty_by_race_2010_2018&bt=20100101&et=20180101&startDwell=0&endDwell=0.02
is slow and

https://staging.earthtime.org/explore#v=40.4479,-79.94045,10.5,latLng&t=5&ps=15&l=bdrk,bdrk_detailed,allegheny_county_pgh,anim_acs_poverty_by_race_2010_2018&bt=20100101&et=20180101&startDwell=0&endDwell=0.02
is too fast because ps=15 is not honored.

**Comment by pdille** [comment]
Fixed in commit ebf0e22

**Comment by rsargent** [comment]
Confirmed!
