### ISSUE TITLE
Look for duplicated layers in the CSV layers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#201]
Some of these might have been split in two for description versus layer definition

**Comment by jjkohler** [comment]
rows 1904-1965 in the default sheet
descriptions need copied

Here's a few examples of currently impacted layers:
https://staging.earthtime.org/explore#v=-12.92015,13.9148,0.159,latLng&t=0.14&ps=50&bt=20120101&et=20121231&l=bdrk,sitc4r2_commodities_4242_exports

https://staging.earthtime.org/explore#v=369124,908872,1067753,1301852,pts&t=0.1&ps=25&l=bdrk,bra_income_inequality_gini&bt=19930101&et=20151231&startDwell=0&endDwell=2&fps=30

**Comment by gabrielo** [comment]
Descriptions for hard-coded layers and some dot maps were in the [default Google sheet](https://docs.google.com/spreadsheets/d/1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE/edit#gid=870361385); rows _1904-1930_.

The following descriptions were absent from the [hard coded layer Google sheet](https://docs.google.com/spreadsheets/d/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY/edit#gid=74523005).
blsat, bdrk, berkeley-earth-temperature-anomaly, berkeley-earth-temperature-anomaly-v2-yearly, chlorophyllConcentration-timemachine, cb, crw, sp, gwp, viirs, wdpa, flg, aflg, h8_16, slr15, slr2, slr4, wo, wc, goes16, dscovr, uf, lan, ar.

fly already had a layer description in the [hard coded layer Google sheet](https://docs.google.com/spreadsheets/d/1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY/edit#gid=74523005).

There are a handful of layers that are defined elsewhere in the default spreadsheet and have a second definition specifying the layer definition. 
sitc4r2_commodities_4242, sitc4r2_commodities_4242_exports, sitc4r2_commodities_4232
I have copied the layer description to the main definition BUT have not deleted the second row. I'm uncertain why they are defined twice and if. deleting them will cause unwanted side effects for the currently deployed system.

**Comment by rsargent** [comment]
FWIW I did delete the second row for census dotmaps, which has resulted in
the temporary regression that these layers no longer have the info icon on
the production earthtime, until we make the release of this branch.

**Comment by gabrielo** [comment]
Duplicated layers have now been deleted.

@jjkohler ok to close or do you want additional testing?

**Comment by jjkohler** [comment]
I believe this issue can now be closed.
