### ISSUE TITLE
Frozen Waypoint in Mobile View (wef-prod)

### ISSUE THREAD

**Issue by andrewcberkley** [CMU-CREATE-Lab/data-visualization-tools#203]
Happy New Year CREATE Lab! I hope 2021 is treating you well, all things considered of course.

I have a waypoint in a story that works fine while in the explore view (https://earthtime.org/#v=35.10252,104.76328,2.217,latLng&t=2.77&ps=25&l=bdrk_detailed,china_startup_funding_amounts&bt=201701&et=202009&startDwell=1&endDwell=3) but is frozen when trying to view on mobile (https://wef-prod.earthtime.org/m/stories/the_chinese_startup_ecosystem). 

The thumbnail seems fine at first ("Finished thumbnail 6242:780730 2021-01-08 09:24:41"), but the mp4 is frozen on the status page as well. I've also tried jiggling it free by renaming the share link identifier a few times (which usually works), but it's still stuck unfortunately.

Any help would be greatly appreciated if you have a moment to take a look (the "wef-prod" spreadsheet can be found at: https://docs.google.com/spreadsheets/d/1walgLKJooOOk0MDpXCni8tgSKMncgZQDWER3H4SoosA/edit#gid=870361385)!

Most importantly though, I hope that 2021 brings you and your loved ones health, happiness, and joy!

-Andrew

**Comment by rsargent** [comment]
Sorry for the problem and thanks for the report.  I'm in meetings until this evening and will check on it then.

**Comment by pdille** [comment]
Hey Andrew. Happy New Year!

Sorry about this. I fixed the sharelinks for you and it looks like the story is working as it should now. Please confirm.

The issue appears to stem from bt=/et= values that are _not_ at a minimum in the form of YYYYMMDD. Note that datasets that are just years are automatically transcribed by the system into YYYYMMDD for exports.

In regards to your dataset here, its time format is YYYYMM and thus that is what is used for bt/et, which ends up only producing a single, static frame. I've seen this before so it all came back to me when I saw the time stamps of the data here.

We'll work on our end to prevent this from happening again but for now if your dataset is only years and months, just tack on "01" to the end of bt/et (see the links in your sheet for this story as examples).

**Comment by andrewcberkley** [comment]
Ah okay that makes sense! Thanks so much for your response Randy and your quick fix Paul! I don't do too many stories with monthly intervals, but that's good to know for future reference!
Hope you're both doing well and hope we can get you guys to Geneva and/or me out to Pittsburgh once life and returned to normal.
