### ISSUE TITLE
Move hardcoded "extras" layers out of index to Google Sheets

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/data-visualization-tools#207]
Extras should no longer be hardcoded. Any new ones are already going into Sheets anyway.

**Comment by pdille** [comment]
@jjkohler This should be done. Thanks for your help moving them into the spreadsheet!

Working on this also uncovered some regressions and those should all be squashed. Do double check things before closing.

**Comment by jjkohler** [comment]
This should now be finished and better than ever.
