### ISSUE TITLE
Auto Legends Only Honoring Width of Title and not other elements

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#210]
![image](https://user-images.githubusercontent.com/42879120/105734879-17924500-5f01-11eb-80fd-5dd5d4166053.png)
https://staging.earthtime.org/explore#v=328414,869844,1047584,1274376,pts&t=0&ps=50&l=blsat,unu_moder_slavery_brazil_bubble_map&bt=20030101&et=20171231&startDwell=0&endDwell=0&fps=30

**Comment by pdille** [comment]
Should be fixed in commit 4d0a6a3

@jjkohler Let me know if you saw this for other legends besides bubble maps.

**Comment by jjkohler** [comment]
This looks like it's been corrected.
