### ISSUE TITLE
Non-mapbox layer legends don't get turned off when visiting mapbox layers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#218]
Go to top50.staging.earthtime.org

Select Stories/TestRS

Click on bdrkmb waypoint
Click on bdrk,anim_total_race
Click on bdrkmb

Note that anim_total_race legend still displays:
![image](https://user-images.githubusercontent.com/324851/107798145-bf917600-6d29-11eb-9cc9-59816e2524b0.png)

**Comment by pdille** [comment]
Addressed in commit ba33e8c902.

Please confirm.
