### ISSUE TITLE
"Clear Active Layers" also clears search results for term currently in search box

### ISSUE THREAD

**Issue by jjkohler** [CMU-CREATE-Lab/data-visualization-tools#220]
This is a regression from previous ET search behavior. Previously, clearing active layers left the search results untouched, facilitating a rapid change to a new, desired layer after clearing the current view.

**Comment by pdille** [comment]
Should be fixed in 4ca144d834dc  

Note that previously in legacy, open categories would also be closed when not searching for a keyword. Now whether you have a search term going or not, open categories remain open when clicking the 'Clear Active Layers' button.

@jjkohler Please confirm.

**Comment by jjkohler** [comment]
This seems to be worked as desired again. @arwright this issue that we saw in the meeting the other day should now be functioning properly for you.
