### ISSUE TITLE
Following newly created share link using mapbox layers shows black map

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#222]
Following
https://jjkohler.earthtime.org/explore#waypoints=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.0&csvlayers=1heLmeuPp7j4itr0cK8H4chugOpp7cU8p_VEB9CFfPlY.1677314377&v=37.83521,-84.747,4.192,latLng&t=2.38&ps=50&l=bdrkmb,well_distance&bt=19900101&et=20171231&startDwell=0&endDwell=0

we get
![image](https://user-images.githubusercontent.com/324851/112520301-a391e300-8d71-11eb-89cc-1d4c2a547548.png)

**Comment by rsargent** [comment]
Maybe this requires a custom layers or custom waypoints spreadsheet link.

**Comment by jjkohler** [comment]
There seem to be two issues here - a more global issue impacting ALL share links generated with a custom layers sheet included in the link. 
Once this is fixed, there may also be an additional mapbox layer specific issue to iron out.

**Comment by rsargent** [comment]
@pdille would you be willing to take this on, at least for the generic
share link breakage?

**Comment by pdille** [comment]
Should be fixed in commit a2e994dd0f

**Comment by rsargent** [comment]
I'll test for mapbox.  Paul says look at console messages.

**Comment by pdille** [comment]
Here is one of such mapbox console errors:

Uncaught TypeError: loadedLayersInIdOrder[i].layer.allVisibleTilesLoaded is not a function
    at EarthTimeImpl.showVisibleLayersLegends (index.ts:328)
    at TimeMachineCanvasLayer.update [as updateHandler_] (index.ts:3264)
    at TimeMachineCanvasLayer.update_ (TimeMachineCanvasLayer.js:536)
    at TimeMachineCanvasLayer.js:161

There is then another error for maxGmapsZoomLevel

Both of these are in Layer.ts but not part of mapbox "layers"

**Comment by rsargent** [comment]
Mapbox share link seems to be working after recent fixes that fixed the console messages.
