### ISSUE TITLE
Acknowledgement when displaying mapbox layers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#224]
When showing mapbox layers, need correct acknowledgement.

**Comment by pdille** [comment]
Addressed in commit 7111dd4

@jjkohler Let me know if more is needed around this

**Comment by jjkohler** [comment]
Could we consider adding a little more image padding on this @pdille? Specifically a few more pixels on top between the mapbox logo and the ET/Create wordmark. Technically it looks like they ask for at least one logo height above to separate.

**Comment by pdille** [comment]
Further tweaks were made in commit 5acb076

@jjkohler

**Comment by pdille** [comment]
I think we are good here. @jjkohler Let me know if we need to reopen.
