### ISSUE TITLE
Data Library search should be the "and" of all terms

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#226]
Searching for race 1990 2010 returns:
![image](https://user-images.githubusercontent.com/324851/114571693-db8b9800-9c44-11eb-8c11-0606e09e4a5e.png)

Expected:  only show layers with titles or descriptions that include "race", "1990" and "2010"

**Comment by pdille** [comment]
Logic fixed in commit 67a3ca534

Please confirm.

**Comment by jjkohler** [comment]
Expected behavior appears to have returned.
