### ISSUE TITLE
Story pane won't scroll vertically with touch

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#232]
Reproduced on iOS/mobile safari and Chrome in mobile debugging mode.

Story pane won't vertically scroll. Removing touch down and touch move handlers from timelapse.js in the Chrome event breakpoint tab fixes it (but at the expense of not being able to touch-move the map :-) )

**Comment by pdille** [comment]
Thanks, noted. See prior #209

**Comment by rsargent** [comment]
Duplicate of #209
