### ISSUE TITLE
First click on specific story waypoint yields playback speed that's too fast

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#235]
Visit this URL, which will land on the "Evict filings (y1)" waypoint in "BEC July 28 2021"
 https://earthtime.org/stories/bec_july_28_2021#waypointIdx=22&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657

Click once on "Freq move arcs", which is 3 waypoints to the right

Observed behavior:  Playback is much too fast -- about 1-2 seconds from 2011 to 2018.

Expected behavior:  Playback should be much slower, closer to 30 seconds from 2011 to 2018

If you click a second time on "Freq move arcs", you'll see the correct playback speed

**Comment by pdille** [comment]
Should be addressed in commit 7edc370 Please confirm.

**Comment by rsargent** [comment]
Confirmed, thanks!  Closing
