### ISSUE TITLE
Clicking on sequence of waypoints prevents animation from correctly cycling

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#236]
Visit
https://earthtime.org/stories/andre_perry_oct_2019#waypointIdx=14&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657

which is the "Rent cost 1990" waypoint from "Andre Perry Oct 2019"

Once it's loaded, click on the very next waypoint to the right, "Rent cost 2010-2017"

Expected behavior:  Animation goes from 2010-2017 and repeats

Observed behavior:  Animation goes from 2010-2017 and then stops at 2017

**Comment by pdille** [comment]
Should be addressed in commit 7edc370 Please confirm.

**Comment by pdille** [comment]
@rsargent When you have the time to test this again, take two is in place. Thanks!

**Comment by rsargent** [comment]
Looks good to us!  Thanks!
