### ISSUE TITLE
tiles.cmucreatelab.org isn't gzipping viirs binary

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#30]
Download took 2.5 mins at 3 mbps (SFO airport wifi)

![image](https://cloud.githubusercontent.com/assets/324851/24533538/7d40bf5c-1596-11e7-88f3-77675120fddf.png)

**Comment by rsargent** [comment]
It looks like this URL isn't actually served locally from tm1 but instead is proxied from hal12?  I vote we move this type of file to the tm1 SSD.  I think this will fix the compression, and be more performant.

**Comment by pdille** [comment]
hal12 no longer serves tiles for this. No longer relevant.
