### ISSUE TITLE
Request:  L, or auto-mode timeout, ought to start from the next waypoint after the current selected one

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#43]
When the user selects a waypoint by clicking or fwd/back, use that waypoint for the auto mode, instead of keeping an independent auto mode state.  So if the user clicks on the 10th waypoint and pressed L, it should move to the 11th.

**Comment by rsargent** [comment]
This is particularly important when we're managing a large screen at a conference.

**Comment by pdille** [comment]
Addressed in commit 951deca1a710260d968994640f301403cf418ef7

The behavior, however, is that if you select the 10th waypoint, press L, it begins automode from that waypoint, not the following one. The intent being, you begin from what you want to start showing. No longer, however, would it start from wherever else it left off in the previous automode cycle.
