### ISSUE TITLE
Ability to include spreadsheets from other spreadsheets for layer definition

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#53]
Proposal:  implement a simple form of inclusion -- optional rows in a spreadsheet that could look something like "include https://docs.google.com/spreadsheets/d/1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE/edit#gid=870361385".

The idea is that if you are developing new non-public CSV or dotmap additions (e.g. davos2019), you could put only the additions and changes in your spreadsheet tab, then include the corresponding main public tab.

...

I like the simple form of inclusion idea. It seems to minimize the number of steps and reduces the chance at human error that was possible when manually copying and pasting from different spreadsheets. I’m all for it!

**Comment by arwright** [comment]
This feature has been added to docs-proxy-flask.  Waypoint sheets with @include <docpath> in the top rows of the '_Waypoint Title_' column or CSV and Dotmap Layer sheets with @include <docpath> in the top rows of the '_Share link identifier_' column are automatically expanded by docs-proxy.  The behavior changed to support this on 3/2/2019.
