### ISSUE TITLE
Allow CSV layers to be mutually-exclusive

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#55]
e.g. 10m and 20m sea level rise shouldn't be on at the same time

**Comment by pdille** [comment]
This was implemented awhile back, during the refactor:

To make use of, in the 'Layer Constraints" column, e.g.: {"layersMutuallyExclusiveWith": ["slr10", "slr15", "slr2", "slr4", "sea_level_rise_20m_v2"]}
