### ISSUE TITLE
Adding apostrophe in Waypoint Title or Annotation Title Doesn't Allow for Rendering of Mobile View

### ISSUE THREAD

**Issue by acberkley** [CMU-CREATE-Lab/data-visualization-tools#57]
I think this might be related to issue #44 . Current work around is to not use apostrophes in the text of either column and the mobile view renders without issue.

**Comment by pdille** [comment]
Can you confirm this is still a problem with the latest mobile scrolling code? 

Note that if you want an apostrophe in the story title (and not a waypoint) you must do that in the "Annotation Title" column, not the "Waypoint Title" column. So for example:

```
Waypoint Title                Annotation Title
##The Worlds Story            The World's Story
```
The field with ## is what is used in the URL and should not have any special characters in the string.

When creating waypoints, either the waypoint title or the annotation title can have apostrophes.

Please confirm though.

**Comment by acberkley** [comment]
Nope, this seems to be fixed via the latest mobile scrolling code! Thank you so much! I'll close the thread now.
