### ISSUE TITLE
Data Library "Show more" unusable on small screen

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#59]
![image](https://user-images.githubusercontent.com/324851/51091864-85c29f80-175e-11e9-9a2f-33b128c8e6f8.png)

**Comment by rsargent** [comment]
What if we did something like this instead maybe?

Stick with the current "less":

![image](https://user-images.githubusercontent.com/324851/51091887-e9e56380-175e-11e9-8450-67d74bd95189.png)

And switch to something like this for "more"?
![image](https://user-images.githubusercontent.com/324851/51091917-624c2480-175f-11e9-91b9-80ef82bc88b9.png)

**Comment by pdille** [comment]
Looks like this was addressed in commit 1edc9d448870 but this report was never closed. Doing so now.
