### ISSUE TITLE
Need ability to show different content on mobile vs desktop stories

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#61]
Sometimes content needs to be different for scroll-mode vs full-interactive, including for layers not supportable by the thumbnail generator (e.g. wind).  Currently we have an optional share-link override for scroll-mode portrait orientation.  Maybe we add an optional share-link override for scroll-mode landscape orientation too.  Or maybe we need to change text content between the two sometimes in which case maybe we could optionally label waypoints "interactive-only" or "scrolling-only".

**Comment by pdille** [comment]
@arwright @rsargent 
Note that with the most current scrolling code, you can achieve this in terms of the visuals being shown.

We have 3 columns in the waypoint spreadsheet that refer to views: "Share View", "Mobile Share View Landscape" and "Mobile Share View Portrait"

Only the "Share View" is used for interactive stories and only the "Mobile" views are used in the scrolling stories. So, you could technically have a view that will only appear in the interactive version and then a completely different view for mobile. And you can even break mobile down further by having an entirely different view for portrait vs landscape.

Different annotations for scrolling vs interactive isn't currently supported though.

**Comment by rsargent** [comment]
I'm going to call this closed, since the most important part of the request -- view -- is done.  We can open a new issue if we need other customizations in the future.
