### ISSUE TITLE
Saving and loading waypoints hides a layer due to different ordering of layers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#64]
Visit  

https://davos2019.earthtime.org/explore#v=1.9241,15.10986,0.238,latLng&t=0&ps=50&l=bdrk,biodiv_lpi_red_over_time,biodiv_lpi_v1_01&bt=20150101&et=20161231&startDwell=0&endDwell=0 and see (correctly)

![image](https://user-images.githubusercontent.com/324851/51544883-243ab900-1e61-11e9-892b-80306aed85a8.png)

Create a share link.  Looks similar to the original, but with layers in a different order:

https://davos2019.earthtime.org/explore#v=1.92409,15.10985,0.238,latLng&t=0.17&ps=50&l=bdrk,biodiv_lpi_v1_01,biodiv_lpi_red_over_time&bt=20150101&et=20161231&startDwell=0&endDwell=0

One of the layers doesn't appear
![image](https://user-images.githubusercontent.com/324851/51545031-6f54cc00-1e61-11e9-9060-7be560042929.png)

**Comment by pdille** [comment]
This was addressed in commit 78f7ee7b5a but never closed. Closing now.
