### ISSUE TITLE
pausing is ignored during dwell times for non standard bt/et loopings

### ISSUE THREAD

**Issue by arwright** [CMU-CREATE-Lab/data-visualization-tools#72]
Desired behavior: space bar should always toggle play/pause.

Actual behavior: if endDwell is non-zero and the playback is in the endDwell period, space bar is ignored.  This makes it very hard to stop playback at the end.  

It's possible that space is also ignored during startDwell.  I have not tested that condition.

**Comment by pdille** [comment]
Do you have an example of this? I don't see this happen with, for example, Landsat or Solar PV on dark map in Chrome.

**Comment by arwright** [comment]
Randy's sending a video.  Here's the link used:
https://earthtime.org/explore#waypointIdx=12&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.0&theme=pittsburgh_assessments&story=default

Wait until it pauses at the end, hit space, then it just keeps going...

**Comment by rsargent** [comment]
I'm familiar with this bug

Video of example
https://drive.google.com/file/d/1Xx7SqLxhuZ0XE3OWmViDOfn_Xo698HIQ/view?usp=sharing

**Comment by pdille** [comment]
Ah, okay, pausing at BT/ET values that are not the standard start/end times (i.e. 0 and duration). Yup, yeah I know of this.

Thanks for making a tracker for this!

**Comment by pdille** [comment]
This should now be addressed in commit 40fc3e4e42 Please confirm.

**Comment by rsargent** [comment]
Confirmed, works!  Tested at earthtime.org
