### ISSUE TITLE
Problem with waypoint share links landing somewhere random

### ISSUE THREAD

**Issue by arwright** [CMU-CREATE-Lab/data-visualization-tools#74]
I have seen a problem several times over the last couple weeks with stories share links with both waypointIdx and waypoints set, like [this one](https://earthtime.org/stories/oh_voting#waypointIdx=3&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657).  These links will sometimes send you to someplace random when you use them instead of the desired destination.

I have only seen this happen when waypoints is pointing to a sheet that has both themes and stories, like [this one](https://docs.google.com/spreadsheets/d/1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE/edit#gid=1073081657).  I have not seen it happen with [the older waypoints sheet](https://docs.google.com/spreadsheets/d/1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE/edit#gid=0) that only uses themes (it predates the addition of themes).

Repro:
-  Go to [earthtime.org/explore](https://earthtime.org/explore)
- Shift-J and paste https://docs.google.com/spreadsheets/d/1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE/edit#gid=1073081657 into the waypoints sheet
- Select the Voting theme, OH Voting story and click on any waypoint except the first
- Click Share and select 'start from current waypoint' checkbox
- Copy and paste the resulting link in a new browser tab

Desired behavior: It should go to the same waypoint you were looking at when you copied the URL out of the share box.

Actual behavior: It will briefly show the desired story/waypoint, but continue on to a waypoint in a different story.

I have also seen this behavior be triggered by editing an existing link of that same form (https://earthtime.org/stories/<storyname>#waypointIdx=<#>&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657) in the URL bar and hitting return.

A pattern I have noticed is that this has only happened when I've been using a themes+stories waypoint sheet.  In that case, the share links will look like "https://earthtime.org/stories/<storyname>", whereas when using a themes-only waypoint sheet, the share links will look like "https://earthtime.org/explore#theme=<themename>&story=default".  Every time I have noticed this behavior it has been with a "https://earthtime.org/stories/<storyname>" URL.

For example, just before entering this report, earthtime.org generated the share link [https://earthtime.org/stories/oh_voting#waypointIdx=3&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657](https://earthtime.org/stories/oh_voting#waypointIdx=3&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657) which should go to the fourth waypoint of the "OH Voting" story in the "Voting" theme.

Using that URL into a browser tab landed on the fourth waypoint of the "US Gender Gaps" story under the "Demographics" theme.

When this behavior happens, it doesn't always land on that same story.  I have seen it land on "Ty's First Story" under "Demographics", and "Distressed Sales" under "Housing."  Unfortunately, I didn't save the share URLs that led to those destinations.

**Comment by pdille** [comment]
This should now be resolved. @arwright, please confirm.

**Comment by arwright** [comment]
Looks good.  Thanks Paul!

I tried it on the URLs in the report and another couple which failed last night.  All worked correctly.

**Comment by pdille** [comment]
Great! Closing the bug thread. Feel free to reopen if something crops back up.
