### ISSUE TITLE
EarthTime hamburger menu doesn't work properly for touch screens

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#76]
Found with Chrome on Surface Pro.
Make EarthTime map window small enough that hamburger menu appears.
Tap hamburger to open menu.
Try to tap Stories or Data Library.  I get a successful tap only about 10% of the time.

**Comment by pdille** [comment]
This should be fixed as of commit 4f80f645e Please confirm.

**Comment by rsargent** [comment]
Confirmed fixed!  Tested on earthtime.org with Surface Pro / Chrome
