### ISSUE TITLE
Timeline position when clicking on a waypoint with shift held should go to same calendar time

### ISSUE THREAD

**Issue by arwright** [CMU-CREATE-Lab/data-visualization-tools#81]
If you are paused in a waypoint showing a layer with a timeline, then hold shift and click on another waypoint with a time line, the absolute point in time (for example, 2010) should be preserved if possible in the second layer.

What it seems to actually do is go to the same position relative to the beginning of each layer's time window, which leads to undesirable behavior if the time windows differ between the layers.

Example:
- Go [here](https://earthtime.org/stories/allegheny_county_mortgages#waypointIdx=9&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657), which is a waypoint showing a layer that goes from 2007 to 2017.
- Pause the time on some date, say 2010.
- Holding down shift, click on the next waypoint (Assessed home values).

Desired behavior:
  Should see assessed home values for 2010.

Actual behavior:
  Actually see assessed home values for 1903.  :(

This causes a lot of problems during exploration and presentations.

**Comment by pdille** [comment]
This should now be addressed in commit 40fc3e4e42 Please confirm.

Note that you may need to hold down shift/'pin the butteryfly' until the waypoint full loads. (i.e. don't just hold shift, click the waypoint and then immediately let go. Hold it for a second longer)

**Comment by rsargent** [comment]
Confirmed fixed!  Tested on earthtime.org:
* Started with this waypoint https://earthtime.org/stories/allegheny_county_mortgages#waypointIdx=39&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657 ("Purchaser Type 2007-2017")
* Paused at 2010
* Scrolled waypoints backwards to Assessed home values, shift-clicked
* Confirmed that timeline now shows 2010
