### ISSUE TITLE
Inaccurate years in share images

### ISSUE THREAD

**Issue by arwright** [CMU-CREATE-Lab/data-visualization-tools#86]
Repro:
* Go to [this url](https://earthtime.org/stories/pittsburgh_evictions_v4#waypointIdx=4&waypoints=1rCiksJv4aXi1usI0_9zdl4v5vuOfiHgMRidiDPt1WfE.1073081657)
* Click on Share, Share as image or video
* Set start and end time to 2010
* Click Generate Image
* Select "Embed time"

Desired behavior: Should show 2010 in the year in the bottom left corner
Actual behavior: Shows 1985 in the bottom left corner

![image](https://user-images.githubusercontent.com/449922/64277667-e7679200-cf18-11e9-81af-c292903e0114.png)

**Comment by pdille** [comment]
I have seen this before with dotmaps, though I can't reproduce in the exact steps you describe.

That said, it appears that dotmaps have a fundamental problem where they do not have a start/end date associated with them. Instead, their timeline (hidden behind the scenes) is actually that of the last layer's timeline that was active. So, for the same dot map layer, depending upon what was last active, you can get very different times in the exported dotmap image.

Should perhaps a column be added in the dotmap csv sheet to indicate a date that the data covers? Animated dot maps are defined in the csv sheet, so they have start/end dates associated with them. It's the static ones that have this problem.

**Comment by arwright** [comment]
Dotmap layers now have a Date column.  This particular URL works to show 2010 now.  :)
