### ISSUE TITLE
Unable to render choropleth with custom .geojson when using monthly intervals

### ISSUE THREAD

**Issue by andrewcberkley** [CMU-CREATE-Lab/data-visualization-tools#88]
Not sure if anyone has run into this problem before, but I’m trying to render a data layer with a custom .geojson file and have the timeline set to monthly intervals. Unfortunately, this keeps on crashing my browser (the readout from the console stalls at “building choropleth tile from geojson”); however, when rendering a similar data layer with the same custom .geojson file with the timeline set to yearly intervals, everything works as it should. Thought this might be a parsing issue, but the sheet being read only has 344 lines. Dates for the month layer and the year layer are formatted as “yyyymm” and “yyyy”, respectively.

Example working waypoint is here:
https://aberkley.earthtime.org/explore#v=39.12089,-6.54955,4.733,latLng&t=0&ps=50&l=average_selling_price_portugal_per_m2_by_year,bdrk&bt=20160101&et=20191231&startDwell=0&endDwell=0

Example of non-working waypoint is here:
https://aberkley.earthtime.org/explore#v=39.12089,-6.54955,4.733,latLng&t=0&ps=50&l=average_selling_price_portugal_per_m2_by_month,bdrk&bt=20160101&et=20191231&startDwell=0&endDwell=0

The sheet with the monthly data is here: https://docs.google.com/spreadsheets/d/1wpboaGA6Cu5HnziEfQNM0GbpLt55jJYl-O_Cu5joMBk/edit#gid=159173096

The sheet with the yearly data is here:
https://docs.google.com/spreadsheets/d/1wpboaGA6Cu5HnziEfQNM0GbpLt55jJYl-O_Cu5joMBk/edit#gid=1413314489

The .geojson file is here (name key is “NAME_2”): https://tiles.earthtime.org/aberkley/data/sub_national_country_geojsons/portugal_county_level_simplified.geojson

![portugal_by_year](https://user-images.githubusercontent.com/26399349/64538498-069d5f80-d31d-11e9-8581-cb538d8251e6.JPG)

^Here is what the working "by year" data layer looks like.

Sharelink idenitfiers in the "aberkley" sheet are: "**average_selling_price_portugal_per_m2_by_month**" and "**average_selling_price_portugal_per_m2_by_year**", which are lines 1704 and 1705, respectively.

Thanks in advance for any help you can provide!

**Comment by pdille** [comment]
@gabrielo @rsargent 
It's running out of memory in earcut.js before it crashes the browser. We had this problem before but perhaps this is different?

**Comment by gabrielo** [comment]
Try reducing the geojson file further. Something less than 4MB might be a good goal. Looks like its 7.3MB right now. https://mapshaper.org/ is a good resource for geojson simpligication.

**Comment by andrewcberkley** [comment]
Was able to push the .geojson to 488 KB without losing too much detail and now it works like a charm! Thanks for your help @pdille and @gabrielo ! I'll be sure to keep the custom .geojson files under 4 MB from now on!
