### ISSUE TITLE
Legend may stay permanently on when switching quickly between waypoints

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#95]
Illah, Jared, Randy all observed yesterday legends sometimes staying on permanently when flipping quickly through Illah's international presentation from Oct 15: 

https://davos2019.earthtime.org/stories/heinz_2019

Illah believes it happens when you switch between layers before they've had a chance to fully load.

Anne reproduced just now -- going to that link and then hitting page-up quickly 15 times -- letting it start loading but go forward before it completed loading, which yielded 2 extra legends in the screeenshot below

![image](https://user-images.githubusercontent.com/324851/66927018-13d4fa80-effd-11e9-9c31-0260d766c870.png)

**Comment by pdille** [comment]
This should be fixed in commit f76c1fc4. Please verify both on davos2019 and the main site. @arwright

**Comment by rsargent** [comment]
Looks great!  Tested at davos2019
