### ISSUE TITLE
Entering earthtime.org through a story sometimes fails to display layers on first waypoint of story

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/data-visualization-tools#98]
Entering earthtime.org through a story sometimes fails to display layers on first waypoint of story.  Neither layer nor legend for layer displays.

Example: https://earthtime.org/stories/new_large_apts#waypoints=15CJzTUXW7b88D8wuJnmG2qQr3El65gaxv_o-awcJybE.0

sometimes shows incorrectly:
![image](https://user-images.githubusercontent.com/324851/70487180-84ab0700-1ac2-11ea-978c-bf07c6c29824.png)

and sometimes shows correctly:
![image](https://user-images.githubusercontent.com/324851/70487238-ae642e00-1ac2-11ea-9c32-4e7bab0cec9a.png)

Split out from possibly related bug https://github.com/CMU-CREATE-Lab/data-visualization-tools/issues/90

**Comment by pdille** [comment]
This should now be fixed as of commit 3e1416989 Please confirm. @arwright

**Comment by arwright** [comment]
Yay!  The sample worked.  I'll keep my open to see if there are relapses or edge cases, and mark this closed.  :)
